<div class="col-md-12">
  <div class="panel panel-sky">
    <h1>Situaciones Económicas</h1>
  
      <div class="panel-heading">
          <h4>Lista de Situaciones Económicas</h4>
          <div class="options">
              <a href="javascript:;" class="panel-collapse"><i class="fa fa-chevron-down"></i></a>
          </div>
      </div>
      <div class="panel-body collapse in">
          <?php echo $this->flashMessenger()->render('success', array('alert', 'alert-dismissable', 'alert-success')); ?>
          <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered datatables" id="example">
              <thead>
                  <tr>
                        <th>Id Sit. Econ.</th>
                        <th>Beneficiario</th>
                        <th>Trabaja</th>                                    
                        <th>Último lugar de Trabajo</th>
                        <th>Ingreso propio</th>
                        <th>Cantidad ingreso</th>
                        <th>Ayuda Social</th>
                        <th>Tipo de ayuda</th>
                        <th>MÁS</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($economias as $economia): ?>
                    <tr class="odd gradeX">
                      <td>
                        <?php echo $economia->getIdEconomia() ?>
                      </td>
                      <td>
                      <?php $beneficiario = $economia->getBeneficiario() ?>  
                        <?php echo $beneficiario->getNombre(); echo "  "; echo $beneficiario->getApellido()?>
                      </td>
                      <td>
                      <!--aqui deberia ir el booleano-->
                        <?php echo $economia->getTrabajo() ?>
                      </td>
                      <td>
                        <?php echo $economia->getNomTrab() ?>
                      </td>

                      <td>
                      <!--aqui deberia ir el booleano-->
                        <?php echo $economia->getIngreso() ?>
                      </td>
                      <td>
                        <?php echo $economia->getCanIng() ?>
                      </td>
                      <td>
                      <!--aqui deberia ir el booleano-->
                        <?php echo $economia->getAyuda() ?>
                      </td>
                      <td>
                        <?php echo $economia->getTipo() ?>
                      </td>
                      <td>
                           <div class="btn-group">
                              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                Más <span class="caret"></span>
                              </button>
                              <ul class="dropdown-menu" role="menu">
                                <!--Opcion uno se dirige a a la vista de Beneficiario-->
                                <li><a  href="<?php echo $this->url('ver-beneficiario')?>"><i class="fa fa-group"></i>Ver Beneficiarios</a></li>
                               <li class="divider"></li>
                       <!--Opcion cinco se dirige a Modificar Economia-->
                                <li><a href="<?php echo $this->url('modE', array('id' => $economia->getIdEconomia())) ?>"><i class="fa fa-cog"></i>Modificar</a></li>
                        <!--Opcion cinco se dirige a Eliminar Economia-->
                                <li><a href="<?php echo $this->url('delE', array('id' => $economia->getIdEconomia())) ?>"><i class="fa fa-times"></i>Eliminar</a></li>
                                
                              </ul>
                            </div>
                      </td>
                    </tr>

                <?php endforeach; ?>
              </tbody>
          </table><!--end table-->
      </div>
  </div>
</div>