<div class="container">
<br>
<h1>Asistencia al Beneficiario</h1>
    <div class="col-xs-12">
        <div class="panel panel-midnightblue">
            <div class="panel-heading">                
                <h4>Formulario de registro para asistencia</h4>
            </div>
            <div class="panel-body">

                <h3>Asistencia al beneficiario</h3>
                <p>Ingrese los datos</p>
                <p class="text-primary">La fecha de entrega es por defecto la actual.</p>

                <?php $form->prepare(); ?>
                    <?php echo $this->form()->openTag($form->setAttributes(['class' => 'form-horizontal row-border', 'data-validate' => 'parsley', 'id' => 'validate-form'])); ?> 
                    <?php $asisMen = $form->get('asistenciamensual');?>
 
                    <div class="form-group">
                        <label for="fieldname" class="col-md-1 control-label">Detalle de Entrega</label>
                        <div class="col-sm-3">
                            <?php echo $this->formRow($asisMen->get('modulo')->setAttributes([ 'class' => 'form-control', 'minlength' => '4'])); ?>
                        </div>                    
                    </div> <div class="form-group">
                        <label for="fieldname" class="col-md-1 control-label">Detalle de Entrega</label>
                        <div class="col-sm-3">
                            <?php echo $this->formRow($asisMen->get('producto')->setAttributes([ 'class' => 'form-control', 'minlength' => '4'])); ?>
                        </div>                    
                    </div>
                    <div class="form-group">
                        <label for="fieldname" class="col-md-1 control-label">Detalle de Entrega</label>
                        <div class="col-sm-3">
                            <?php echo $this->formRow($asisMen->get('otro')->setAttributes([ 'class' => 'form-control', 'minlength' => '4'])); ?>
                        </div>                    
                    </div>
            </div>
            <div class="panel-footer">
                <div class="row">
                    <div class="col-sm-6 col-sm-offset-3">
                        <div class="btn-toolbar">
                            <button type="submit" class="btn-primary btn" >Registrar</button>
                        </div>
                    </div>
                </div>
                <?php echo $this->form()->closeTag(); ?> 
            </div>
        </div>

    </div>
</div>
