<div class="container">
<br>
<h1>Asistencia al Beneficiario</h1>
    <div class="col-xs-12">
        <div class="panel panel-midnightblue">
            <div class="panel-heading">                
                <h4>Formulario de registro para asistencia</h4>
            </div>
            <div class="panel-body">

                <h3>Asistencia al beneficiario</h3>
                <p>Ingrese los datos</p>
                <p class="text-primary">La fecha de entrega es por defecto la actual.</p>

                <?php $form->prepare(); ?>
                    <?php echo $this->form()->openTag($form->setAttributes(['class' => 'form-horizontal row-border', 'data-validate' => 'parsley', 'id' => 'validate-form'])); ?> 
                    <?php $empleado = $form->get('asistenciamensual'); ?>
                    
                    <div class="form-group">
                        <label class="col-sm-3 control-label">
                            Detalle de entrega
                        </label>
                        <div class="col-sm-6">
                            <?php echo $this->formRow($empleado->get('detalleEntrega')->setAttributes([ 'ata-minlength' => '1', 'required' => 'required', 'class' => 'form-control'])); ?>
                        </div>
                    </div> 
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Radio</label>
                        <div class="col-sm-6">
                            <div class="radio">
                              <label>
                                <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked>
                                    <div class="col-sm-6">
                                    <?php echo $this->formRow($empleado->get('modulo')->setAttributes([ 'ata-minlength' => '1', 'required' => 'required', 'class' => 'form-control'])); ?>
                                    </div>
                                </input>
                              </label>
                            </div>
                            <div class="radio">
                              <label>
                                <input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">
                                Option two can be something else
                              </label>
                            </div>
                        </div>
                    </div>   
                      
            </div>
            <div class="panel-footer">
                <div class="row">
                    <div class="col-sm-6 col-sm-offset-3">
                        <div class="btn-toolbar">
                            <button type="submit" class="btn-primary btn" >Registrar</button>
                        </div>
                    </div>
                </div>
                <?php echo $this->form()->closeTag(); ?> 
            </div>
        </div>
    </div>
</div>