<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EstadoCivil extends \Application\Entity\EstadoCivil implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'idEstado', 'descripcion', 'idBeneficiario', 'nroF');
        }

        return array('__isInitialized__', 'idEstado', 'descripcion', 'idBeneficiario', 'nroF');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EstadoCivil $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdEstado()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdEstado();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEstado', array());

        return parent::getIdEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', array($descripcion));

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', array());

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function addIdBeneficiario(\Application\Entity\Beneficiario $idBeneficiario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIdBeneficiario', array($idBeneficiario));

        return parent::addIdBeneficiario($idBeneficiario);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIdBeneficiario(\Application\Entity\Beneficiario $idBeneficiario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIdBeneficiario', array($idBeneficiario));

        return parent::removeIdBeneficiario($idBeneficiario);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdBeneficiario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdBeneficiario', array());

        return parent::getIdBeneficiario();
    }

    /**
     * {@inheritDoc}
     */
    public function addNroF(\Application\Entity\Familia $nroF)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addNroF', array($nroF));

        return parent::addNroF($nroF);
    }

    /**
     * {@inheritDoc}
     */
    public function removeNroF(\Application\Entity\Familia $nroF)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeNroF', array($nroF));

        return parent::removeNroF($nroF);
    }

    /**
     * {@inheritDoc}
     */
    public function getNroF()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNroF', array());

        return parent::getNroF();
    }

}
