<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Beneficiario extends \Application\Entity\Beneficiario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'idBeneficiario', 'dni', 'nombre', 'apellido', 'lugnac', 'fechanac', 'estadocivil', 'educacion', 'profession', 'domben', 'ciudad', 'provincia', 'resben', 'telfben', 'fam', '' . "\0" . 'Application\\Entity\\Beneficiario' . "\0" . 'estado', '' . "\0" . 'Application\\Entity\\Beneficiario' . "\0" . 'fechaAlta');
        }

        return array('__isInitialized__', 'idBeneficiario', 'dni', 'nombre', 'apellido', 'lugnac', 'fechanac', 'estadocivil', 'educacion', 'profession', 'domben', 'ciudad', 'provincia', 'resben', 'telfben', 'fam', '' . "\0" . 'Application\\Entity\\Beneficiario' . "\0" . 'estado', '' . "\0" . 'Application\\Entity\\Beneficiario' . "\0" . 'fechaAlta');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Beneficiario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdBeneficiario()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdBeneficiario();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdBeneficiario', array());

        return parent::getIdBeneficiario();
    }

    /**
     * {@inheritDoc}
     */
    public function setDni($dni)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDni', array($dni));

        return parent::setDni($dni);
    }

    /**
     * {@inheritDoc}
     */
    public function getDni()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDni', array());

        return parent::getDni();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellido($apellido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellido', array($apellido));

        return parent::setApellido($apellido);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellido', array());

        return parent::getApellido();
    }

    /**
     * {@inheritDoc}
     */
    public function setLugnac($lugnac)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLugnac', array($lugnac));

        return parent::setLugnac($lugnac);
    }

    /**
     * {@inheritDoc}
     */
    public function getLugnac()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLugnac', array());

        return parent::getLugnac();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechanac($fechanac)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechanac', array($fechanac));

        return parent::setFechanac($fechanac);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechanac()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechanac', array());

        return parent::getFechanac();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomben($domben)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomben', array($domben));

        return parent::setDomben($domben);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomben()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomben', array());

        return parent::getDomben();
    }

    /**
     * {@inheritDoc}
     */
    public function setCiudad($ciudad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCiudad', array($ciudad));

        return parent::setCiudad($ciudad);
    }

    /**
     * {@inheritDoc}
     */
    public function getCiudad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCiudad', array());

        return parent::getCiudad();
    }

    /**
     * {@inheritDoc}
     */
    public function setProvincia($provincia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProvincia', array($provincia));

        return parent::setProvincia($provincia);
    }

    /**
     * {@inheritDoc}
     */
    public function getProvincia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProvincia', array());

        return parent::getProvincia();
    }

    /**
     * {@inheritDoc}
     */
    public function setResben($resben)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResben', array($resben));

        return parent::setResben($resben);
    }

    /**
     * {@inheritDoc}
     */
    public function getResben()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResben', array());

        return parent::getResben();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelfben($telfben)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelfben', array($telfben));

        return parent::setTelfben($telfben);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelfben()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelfben', array());

        return parent::getTelfben();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', array($estado));

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', array());

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaAlta($fechaAlta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaAlta', array($fechaAlta));

        return parent::setFechaAlta($fechaAlta);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaAlta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaAlta', array());

        return parent::getFechaAlta();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadocivil(\Application\Entity\EstadoCivil $estadocivil = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadocivil', array($estadocivil));

        return parent::setEstadocivil($estadocivil);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadocivil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadocivil', array());

        return parent::getEstadocivil();
    }

    /**
     * {@inheritDoc}
     */
    public function setEducacion(\Application\Entity\Educacion $educacion = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEducacion', array($educacion));

        return parent::setEducacion($educacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getEducacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEducacion', array());

        return parent::getEducacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfession(\Application\Entity\Profesion $profession = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfession', array($profession));

        return parent::setProfession($profession);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfession()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfession', array());

        return parent::getProfession();
    }

    /**
     * {@inheritDoc}
     */
    public function addFam(\Application\Entity\Familia $fam)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFam', array($fam));

        return parent::addFam($fam);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFam(\Application\Entity\Familia $fam)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFam', array($fam));

        return parent::removeFam($fam);
    }

    /**
     * {@inheritDoc}
     */
    public function getFam()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFam', array());

        return parent::getFam();
    }

}
