<?php

namespace Application\Repository;

/**
 * AsistenteSocial
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsistenteSocial extends \Doctrine\ORM\EntityRepository
{
}
