<?php

namespace Application\Repository;

/**
 * Empleado
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Empleado extends \Doctrine\ORM\EntityRepository
{
    public function getQueryDarDeBaja($ide) {
        
        $dql = "UPDATE Application\Entity\Empleado e SET e.activo = 0 WHERE e.id = ?1";
        $this->_em = $this->getEntityManager();
        return $this->_em->createQuery($dql)
                        ->setParameter(1, $ide)
                        ->getResult();
    }
}
