<?php

namespace Application\Repository;

/**
 * MesaEntrada
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MesaEntrada extends \Doctrine\ORM\EntityRepository
{
}
