<?php

namespace Application\Repository;

/**
 * Producto
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Producto extends \Doctrine\ORM\EntityRepository
{
    public function getQueryDarDeBaja($idp) {
        $dql = "UPDATE Application\Entity\Producto p SET p.activo = 0 WHERE p.id_producto = ?1";
        $this->_em = $this->getEntityManager();
        return $this->_em->createQuery($dql)
                        ->setParameter(1, $idp)
                        ->getResult();
    }
}
