<div class="col-md-12">
  <div class="panel panel-sky">
    <h1>Empleado</h1>
  
      <div class="panel-heading">
          <h4>Lista empleados</h4>
          <div class="options">
              <a href="javascript:;" class="panel-collapse"><i class="fa fa-chevron-down"></i></a>
          </div>
      </div>
      <div class="panel-body collapse in">
          <?php echo $this->flashMessenger()->render('success', array('alert', 'alert-dismissable', 'alert-success')); ?>
          <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered datatables" id="example">
              <thead>
                  <tr>
                      <th>Id empleado</th>
                      <th>DNI</th>
                      <th>Nombre</th>
                      <th>Apellido</th>
                      <th>Sector  </th>
                      <th>Acciones</th>
                  </tr>
              </thead>
              <tbody>
                
                <?php foreach ($empleados as $empleado): ?>
              
                  <tr class="even gradeC"> 
                    <td>
                      <?php echo $empleado->getId() ?>
                    </td>
                    <td>
                      <?php echo $empleado->getDni() ?>
                    </td>
                    <td>
                      <?php echo $empleado->getNombre() ?>
                    </td>
                    <td>
                      <?php echo $empleado->getApellido() ?>
                    </td>
                    <td>
                      <?php  $sector = $empleado->getSector() 
                        ?>  
                      <?php echo $sector->getNombre() ?>                                      
                    </td>
                    <td>
                        <a class="btn btn-warning-alt btn-label" href="<?php echo $this->url('editar_empleado', array(
                      'id' => $empleado->getId())) ?>"><i class="fa fa-cog"></i>Editar</a>     
                        <a class="btn btn-danger-alt btn-label" href="<?php echo $this->url('eliminar_empleado', 
                                array('id' => $empleado->getId())) ?>"><i class="fa fa-times"></i>Eliminar</a>                                          
                    </td>
                  </tr>
                <?php endforeach; ?>
                  
              </tbody>
          </table><!--end table-->
      </div>
  </div>
</div>