<?php echo $this->flashMessenger()->render('success', array('alert', 'alert-dismissable', 'alert-success')); ?>
<?php echo $this->flashMessenger()->render('error', array('alert', 'alert-dismissable', 'alert-danger')); ?>    

<div class="focusedform">
    <div class="verticalcenter">
        <a href=""><img src="/img/logo-big.png" alt="Logo" class="brand" /></a>
        <div class="panel panel-primary">
            <div class="panel-body">
                <h4 class="text-center" style="margin-bottom: 25px;">Log in to get started or <a href="extras-signupform.htm">Sign Up</a></h4>
                <?php $form->prepare(); ?>
                <?php echo $this->form()->openTag($form->setAttributes(['class' => 'form-horizontal', 'style' => 'margin-bottom: 0px !important;'])); ?>				
                <div class="form-group">
                    <div class="col-sm-12">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-user"></i></span>
                            <?php echo $this->formRow($form->get('email')->setAttributes(['class' => 'form-control', 'placeholder' => 'Correo electrónico', 'type' => 'text'])); ?> 
                            <!--<input type="text" class="form-control" id="username" placeholder="Username">-->
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-12">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                            <?php echo $this->formRow($form->get('password')->setAttributes(['class' => 'form-control', 'placeholder' => 'Contraseña', 'type' => 'password'])); ?>
                            <!--<input type="password" class="form-control" id="password" placeholder="Password">-->
                        </div>
                    </div>
                </div>

                <div class="clearfix">
                    <div class="pull-right"><label><input type="checkbox" style="margin-bottom: 20px" checked=""> Remember Me</label></div>
                </div>						
            </div>
            <div class="panel-footer">
                <a href="extras-forgotpassword.htm" class="pull-left btn btn-link" style="padding-left:0">Forgot password?</a>

                <div class="pull-right">
                    <a href="#" class="btn btn-default">Reset</a>
                    <button type="submit" class="btn-primary btn" >Registrar</button>					 
                </div>
                <?php echo $this->formRow($form->get('login_csrf')) ?>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>      
</div>