
<div class="panel panel-primary">
    <div class="panel-heading">
        <h4>
            <ul class="nav nav-tabs">
                <li class="active"><a href="#home98" data-toggle="tab">Lista de modulos</a></li>
                <li><a href="#profile98" data-toggle="tab">Modulo nuevo</a></li>
                <li><a href="#messages98" data-toggle="tab">Messages</a></li>
            </ul>
        </h4>
        <div class="options">
            <a href="#"><i class="fa fa-cogs"></i></a>
        </div>
    </div>
    <div class="panel-body">
        <div class="tab-content">
            <div class="tab-pane active" id="home98">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                <h4>Nuevo produco para el modulo</h4>

                            </div>
                            <div class="panel-body">
                                <h3>Modulo</h3>
                                <p>Ingrese los datos del nuevo modulo</p>
                                <p class="text-primary">El ID de modulo se genera automáticamente.</p>
                                <br>
                                <?php $form->prepare() ?>
                                <?php echo $this->form()->openTag($form->setAttributes(['id' => 'surveyForm', 'class' => 'form-horizontal', 'data-validate' => 'parsley', 'id' => 'validate-form'])) ?>
                                <?php

                                $productoDeModulo= $form->get('productodemodulo'); ?>
                                    <?php echo $this->formRow($productoDeModulo->get('moduloId')->setAttributes(['value'=> $modulo->getIdModulo()])); ?> 
                                    <?php echo $this->formRow($productoDeModulo->get('idProducto')->setAttributes(['value'=> $producto->getIdProducto()])); ?> 

                                <div class="form-group">
                                    <label for="focusedinput" class="col-sm-3 control-label">Nombre del producto</label>
                                    <div class="col-sm-6">

                                        <?php echo $this->formRow($productoDeModulo->get('producto')->setAttributes(['placeholder' => 'Ingrese el nombre del tipo de modulo', 'id' => 'focusedinput', 'ata-minlength' => '2',
                                                    'required' => 'required', 'class' => 'form-control', 'type' => 'text','value'=>$producto->getNombre()]));
                                        ?> 
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="focusedinput" class="col-sm-3 control-label">Cantidad de producto</label>
                                    <div class="col-sm-6">

                                        <?php echo $this->formRow($productoDeModulo->get('cantidad')->setAttributes(['placeholder' => 'Ingrese la cantidad', 'data-type'=>'digits','id' => 'focusedinput', 'ata-minlength' => '2',
                                                    'required' => 'required', 'class' => 'form-control', 'type' => 'text']));
                                        ?> 
                                    </div>
                                </div>
                                <div class="panel-footer">
                                <div class="row">
                                    <div class="col-sm-6 col-sm-offset-3">
                                        <div class="btn-toolbar">
                                            <button type="submit" class="btn-primary btn">Registrar</button>

                                        </div>
                                    </div>
                                </div>
                            </div>

                            </div>
                         

                        <?php echo $this->form()->closeTag(); ?> 
                        </div>
                    </div>

                </div>

            </div>
            <div class="tab-pane" id="profile98">Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, porro eveniet debitis quas sed harum nobis libero voluptatibus dolorum odio at veniam aut id corrupti hic esse quisquam fugiat.</div>
            <div class="tab-pane" id="messages98">Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur ipsam consectetur sint. Nobis facere illo iste quaerat sapiente doloribus deserunt et nam obcaecati recusandae possimus aperiam similique.</div>
        </div>
    </div>
</div>

