<div class="container">
            <div class="row">
              <div class="col-md-12">
                    <div class="panel panel-sky">
                        <div class="panel-heading">
                            <h4>Lista de productos en los modulos</h4>
                            <div class="options">   
                                <a href="javascript:;"><i class="fa fa-cog"></i></a>
                                <a href="javascript:;"><i class="fa fa-wrench"></i></a>
                                <a href="javascript:;" class="panel-collapse"><i class="fa fa-chevron-down"></i></a>
                            </div>
                        </div>
                        <div class="panel-body collapse in">
                            <?php echo $this->flashMessenger()->render('success', array('alert','alert-dismissable', 'alert-success')); ?>
                            <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered datatables" id="editable">
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Nombre del modulo</th>
                                        <th>Producto</th>
                                        <th>Tipo</th>
                                        <th>Cantidad</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php// var_dump($lpenmodulos);die;?>
                                    <?php foreach($lpenmodulos as $lpenmodulo): ?>
                                        <tr class="odd gradeX">
                                            <?php $modulo = $lpenmodulo->getModuloId()?> 
                                            <td><?php echo $modulo->getIdModulo() ?></td>                                                                          
                                            <td><?php echo $modulo->getNombre() ?></td>                                            
                                            <?php $producto=$lpenmodulo->getIdProducto()?>                                            
                                            <td><?php echo $producto->getNombre() ?></td>                                            
                                            <td><?php echo $modulo->getTipo() ?></td>
                                            <td><?php echo $lpenmodulo->getCantidad() ?></td>
                                        </tr>
                                     <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div> <!-- container -->