<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h4>Nuevo Modulo</h4>

            </div>
            <div class="panel-body">
                <h3>Modulo</h3>
                <p>Ingrese los datos del nuevo modulo</p>
                <p class="text-primary">El ID de modulo se genera automáticamente.</p>
                <br>
                <?php $form->prepare() ?>
                <?php echo $this->form()->openTag($form->setAttributes(['id'=>'surveyForm','class' => 'form-horizontal', 'data-validate' => 'parsley', 'id' => 'validate-form'])) ?>
                <?php //var_dump($form);die;
                $modulo = $form->get('modulo');             
                ?>

                <div class="form-group">
                    <label for="focusedinput" class="col-sm-3 control-label">Nombre del modulo</label>
                    <div class="col-sm-6">

                        <?php echo $this->formRow($modulo->get('tipo')->setAttributes(['placeholder' => 'Ingrese el nombre del tipo de modulo', 'id' => 'focusedinput', 'ata-minlength' => '2',
                                    'required' => 'required', 'class' => 'form-control', 'type' => 'text'])); ?> 
                    </div>
                </div>

                <div class="form-group">
                    <label for="txtarea1" class="col-sm-3 control-label">Producto</label>
                    <div class="col-sm-6"><?php echo $this->formRow($modulo->get('producto')->setAttributes(['placeholder' => 'Ingrese  la descripcion', 'ata-minlength' => '2', 'required' => 'required',
                                    'class' => 'form-control']));?>
                    </div>
                    <div class="col-md-1">
                        <button type="button" class="btn btn-default addButton"><i class="fa fa-plus"></i></button>
                    </div>
                </div>     

		  

            </div>
            <div class="panel-footer">
                <div class="row">
                    <div class="col-sm-6 col-sm-offset-3">
                        <div class="btn-toolbar">
                            <button type="submit" class="btn-primary btn">Registrar</button>

                        </div>
                    </div>
                </div>
            </div>
            
<?php echo $this->form()->closeTag(); ?> 
        </div>
    </div>
    <script>
    $(document).ready(function() {
    // The maximum number of options
    var MAX_OPTIONS = 5;

    $('#surveyForm')
        .formValidation({
            framework: 'bootstrap',
            icon: {
                valid: 'glyphicon glyphicon-ok',
                invalid: 'glyphicon glyphicon-remove',
                validating: 'glyphicon glyphicon-refresh'
            },
            fields: {
                question: {
                    validators: {
                        notEmpty: {
                            message: 'The question required and cannot be empty'
                        }
                    }
                },
                'modulo[producto]': {
                    validators: {
                        notEmpty: {
                            message: 'The option required and cannot be empty'
                        },
                        stringLength: {
                            max: 100,
                            message: 'The option must be less than 100 characters long'
                        }
                    }
                }
            }
        })

        // Add button click handler
        .on('click', '.addButton', function() {
            var $template = $('#optionTemplate'),
                $clone    = $template
                                .clone()
                                .removeClass('hide')
                                .removeAttr('id')
                                .insertBefore($template),
                $option   = $clone.find('[name="modulo[producto]"]');

            // Add new field
            $('#surveyForm').formValidation('addField', $option);
        })

        // Remove button click handler
        .on('click', '.removeButton', function() {
            var $row    = $(this).parents('.form-group'),
                $option = $row.find('[name="modulo[producto]"]');

            // Remove element containing the option
            $row.remove();

            // Remove field
            $('#surveyForm').formValidation('removeField', $option);
        })

        // Called after adding new field
        .on('added.field.fv', function(e, data) {
            // data.field   --> The field name
            // data.element --> The new field element
            // data.options --> The new field options

            if (data.field === 'modulo[producto]') {
                if ($('#surveyForm').find(':visible[name="modulo[producto]"]').length >= MAX_OPTIONS) {
                    $('#surveyForm').find('.addButton').attr('disabled', 'disabled');
                }
            }
        })

        // Called after removing the field
        .on('removed.field.fv', function(e, data) {
           if (data.field === 'modulo[producto]') {
                if ($('#surveyForm').find(':visible[name="modulo[producto]"]').length < MAX_OPTIONS) {
                    $('#surveyForm').find('.addButton').removeAttr('disabled');
                }
            }
        });
});
</script>
</div
