<div class="panel panel-primary">
  <div class="panel-heading">
     <h4>Legajo de Beneficiario n° <?php echo $beneficiarioPrueba[0]->getIdBeneficiario() ?></h4>
    <div class="options">
      <ul class="nav nav-tabs">
          <li class="active">
            <a href="#beneficiario1" data-toggle="tab">Beneficiario</a>
          </li>
          <li>
            <a href="#familia1" data-toggle="tab">Familia</a>
          </li>
          <li>
            <a href="#economia1" data-toggle="tab">Sit. Económica</a>
          </li>
          <li>
            <a href="#sanidad1" data-toggle="tab">Sit. Sanitaria</a>
          </li>
          <li>
            <a href="#vivienda1" data-toggle="tab">Sit. Vivienda</a>
          </li>            
      </ul>
    </div>
  </div>
  <div class="panel-body">
    <div class="tab-content">
                                                <!--Datos del beneficiario-->  
          <div class="tab-pane active" id="beneficiario1">
                                                      <!--Datos personales-->
                <div class="form-group col-sm-3">
                  <strong><h4>Nombre y Apellido</h4></strong>
                    <div class="col-sm-6" >
                      <?php echo $beneficiarioPrueba[0]->getNombre(); ?>
                    </div>
                    <div class="col-sm-1" >
                      <?php echo' '; echo $beneficiarioPrueba[0]->getApellido();?>
                    </div> 
                </div>
                <div class="form-group col-sm-2">               
                  <strong><h4>DNI</h4></strong>
                    <div class="col-sm-1">
                     <?php echo $beneficiarioPrueba[0]->getDni() ?>
                    </div>
                </div>
                <div class="form-group col-md-3">
                    <strong><h4>Lugar de Nacimiento</h4></strong>
                        <div class="col-sm-1" >
                            <?php echo $beneficiarioPrueba[0]->getLugnac() ?>
                        </div>
                </div>
                <div class="form-group col-sm-3">
                    <strong><h4>Fecha de Nacimiento</h4></strong>
                        <div class="col-sm-6">
                            <?php  $fechanac=$beneficiarioPrueba[0]->getFechanac()  ?>
                            <?php echo $fechanac->format('d-m-Y')  ?>
                              <div class="input-group date"></div>
                        </div>
                </div>
             
                <div class="form-group col-md-12">
                  <strong><h4>Estado civil</h4></strong>
                    <div class="col-sm-2">
                    <?php $estC=$beneficiarioPrueba[0]->getEstadocivil(); ?> 
                      <?php echo $estC->getDescripcion(); ?>
                    </div>
                </div>  
              
                            <!--Datos del domicilio de Beneficiario-->
                <div class="form-group col-md-3">
                  <strong><h4>Domicilio</h4></strong>
                    <div class="col-sm-8">
                      <?php echo $beneficiarioPrueba[0]->getDomben(); ?> 
                    </div>
                </div>
                <div class="form-group col-md-2">                    
                  <strong><h4>Ciudad</h4></strong>
                    <div class="col-sm-4">
                      <?php echo $beneficiarioPrueba[0]->getCiudad(); ?>
                    </div>
                </div>
                <div class="form-group col-md-2">                     
                  <strong><h4>Provincia</h4></strong>
                    <div class="col-md-8">
                      <?php echo $beneficiarioPrueba[0]->getProvincia(); ?>
                    </div>       
                </div> 
                <div class="form-group col-xs-3">
                  <strong><h4>Residencia en Catriel</h4></strong>
                    <div class="col-sm-2">
                      <?php echo $beneficiarioPrueba[0]->getResben(); ?>
                    </div>
                </div>
                <div class="form-group col-xs-2">                    
                  <strong><h4>Telefono</h4></strong>
                    <div class="col-sm-3">   
                      <?php echo $beneficiarioPrueba[0]->getTelfben(); ?>
                    </div>

                </div>
                                <!--Datos de Estudio y Oficio del Beneficiario-->
                <div class="form-group col-md-12">
                  <strong><h4>Tipo de Estudios</h4></strong>
                    <div class="col-sm-2">
                      <?php $est=$beneficiarioPrueba[0]->getEducacion(); ?> 
                      <?php echo $est->getDescripcion(); ?>                    
                    </div> 
                </div> 
                <div class="form-group col-md-12">
                  <strong><h4>Oficio</h4></strong>
                    <div class="col-sm-2">
                      <?php $of=$beneficiarioPrueba[0]->getProfession(); ?> 
                      <?php echo $of->getDescripcion(); ?>                                              
                    </div> 
                </div>      
          </div>
               <!--Familia-->
        <div class="tab-pane" id="familia1">
          <div class="form-group">    
                <table class="table table-condensed">
                  <thead>
                      <tr>
                            <th>Nro Legajo</th>
                            <th>Nombre y Apellido</th>
                            <th>DNI</th>                                    
                            <th>Lugar de Nacimiento</th>
                            <th>Fecha de Nacimiento</th>                        
                            <th>Estado Civil</th>
                            <th>Educación</th>
                            <th>Relación</th>
                      </tr>
                  </thead>
                  <tbody>

                  <?php for($i=0;$i<count($familias);$i++) {?>
                      <tr class="odd gradeX">
                          <td> 
                            <!--Legajo Familia-->  
                            <?php echo $familias[$i]->getNroF();?>

                          </td>
                          <td>
                            <!--Nombre y Apellido Familia--> 
                            <?php echo $familias[$i]->getNombre(),"      ",$familias[$i]->getApellido();?>

                          </td>
                          <td>
                              <!--DNI Familia-->
                              <?php echo $familias[$i]->getDni();?>

                          </td>
                          <td>
                              <!--Lugar de Nac Familia--> 
                              <?php echo $familias[$i]->getLugnac(); ?>
                          </td>
                          <td>
                                <!--Fecha de Nac Familia-->
                              <?php  $fechaNacimiento = $familias[$i]->getFechanac();  ?>
                              
                              <?php echo $fechaNacimiento->format('d-m-Y'); ?>
                          </td>
                          <td>
                                <!--Estado civil Familia-->
                              <?php $estado = $familias[$i]->getEstadocivil(); ?>
                              <?php echo $estado->getDescripcion(); ?>
                          </td> 
                          <td>
                                  <!--Educacion Familia-->
                              <?php $educacion =$familias[$i]->getEducacion(); ?>
                              <?php echo $educacion->getDescripcion(); ?>
                          </td>                                                                 
                          <td>
                                  <!--Relacion Familia-->
                              <?php $relacion =  $familias[$i]->getRelacion(); ?> 
                              <?php echo $relacion->getDescripcion(); ?>            
                          </td>   

                      </tr>
                      <?php } ?>
                </tbody>
              </table>
          </div>
        </div>

                <!--Economia-->
        <div class="tab-pane" id="economia1">
                                            <!--Datos de la situacion economica-->                                      
          <div class="form-group col-md-3">
            <strong><h4>¿Trabaja actualmente?</h4></strong>
              <div class="col-sm-1">
                   <?php  if ($trab=$economia[0]->getTrabajo()=='1') {
                                    echo 'Si';
                                 } else {
                                   echo 'No';
                                 }
                    ?>
              </div>
          </div>
          <div class="form-group col-md-12">          
            <strong><h4>Nombre del ultimo lugar de trabajo</h4></strong>
              <div class="col-md-9">
              <?php echo $nomtrab=$economia[0]->getNomTrab(); ?>
              </div>
          </div>
                      <!--Datos sobre el ingreso que tiene-->
          <div class="form-group col-md-4">
            <strong><h4>¿Recibe algún Ingreso Económico?</h4></strong>
              <div class="col-sm-1">
                                   <?php  if ($ing=$economia[0]->getIngreso()=='1') {
                                    echo 'Si';
                                 } else {
                                   echo 'No';
                                 }
                    ?>
              </div>
          </div>
          <div class="form-group col-md-3">          
            <strong><h4>Ingreso Económico</h4></strong>
              <div class="col-sm-2">
               <?php echo $canting=$economia[0]->getCanIng(); ?>
              </div>
          </div>    
          <div class="form-group col-md-3">  
            <strong><h4>Periodicidad que lo Recibe</h4></strong>
              <div class="col-sm-3">
               <?php echo $tiemping=$economia[0]->getTiempoIng(); ?>
              </div>                                  
          </div>
          <div class="form-group col-md-12">
            <strong><h4>Otras Observaciones Sobre los Ingresos</h4></strong>
              <div class="col-sm-12">
               <?php echo $obser=$economia[0]->getObser1(); ?>
              </div>
          </div>                        
                  <!--Datos de otros tipos de ingreso-->
          <div class="form-group col-md-12">
            <strong><h4>¿Actualmente recibe otro tipo de ayuda Económica?</h4></strong>
                <div class="col-sx-1">
                                   <?php  if ($ayuda=$economia[0]->getAyuda()=='1') {
                                    echo 'Si';
                                 } else {
                                   echo 'No';
                                 }
                    ?>
                </div>  
          </div>      
          <div class="form-group col-md-4">                                     
              <strong><h4>Tipo de Ayuda</h4></strong>
                <div class="col-sm-5">
                   <?php echo $tipayuda=$economia[0]->getTipo(); ?>
                </div>
          </div>
          <div class="form-group col-md-3"> 
              <strong><h4>Cantidad aproximada</h4></strong>
                <div class="col-sm-2">
                  <?php echo $cantayuda=$economia[0]->getCanAyuda(); ?>
                </div>
          </div>
          <div class="form-group col-md-4">  
              <strong><h4>Periodicidad que lo recibe</h4></strong>
                <div class="col-sm-2">
                  <?php echo $tiemayuda=$economia[0]->getTiempoA(); ?>
                </div>                                  
          </div>
          <div class="form-group col-md-12">
              <strong><h4>Otras Observaciones sobre la ayuda Social</h4></strong>
                <div class="col-sm-12">
                  <?php echo $obs2=$economia[0]->getObser2(); ?>
                </div>
          </div>
                    <!--Otras observaciones-->
          <div class="form-group col-md-12">
            <strong><h4>Observacion Generales</h4></strong>
              <div class="col-sm-12">
                  <?php echo $obs3=$economia[0]->getObser3(); ?>              
              </div>
          </div>             
        </div>

                <!--Sanidad-->
        <div class="tab-pane" id="sanidad1">
                              <!--Datos de la cobertura social-->
          <div class="form-group col-md-3">
            <strong><h4>Cobertura de Obra Social</h4></strong>
              <div class="col-sx-1">
                    <?php  if ($cobert=$sanidad[0]->getCobertura()=='1') {
                                    echo 'Si';
                                 } else {
                                   echo 'No';
                                 }
                    ?>                          
              </div>
          </div>
          <div class="form-group col-md-3">
            <strong><h4>Nombre de Obra Social</h4></strong>
              <div class="col-sm-3">
                   <?php echo $nomobra=$sanidad[0]->getObraS(); ?>                                         
              </div>
          </div>
          <div class="form-group col-md-12">
            <strong><h4>Miembro Poseedor de la Obra Social</h4></strong>
              <div class="col-sm-3">
                   <?php echo $posedorobra=$sanidad[0]->getFamOS(); ?>                                        
              </div> 
          </div>
                                    <!--Datos sobre la atencion medica-->
          <div class="form-group col-md-3">
            <strong><h4>Atención en el Hospital de Catriel</h4></strong>
              <div class="col-sm-2">
                    <?php  if ($hospital=$sanidad[0]->getAtenHC()=='1') {
                                    echo 'Si';
                                 } else {
                                   echo 'No';
                                 }
                    ?>                                             
              </div>
          </div>
          <div class="form-group col-md-3">          
            <strong><h4>Atención en otros Centros de Salud</h4></strong>
              <div class="col-sm-2">
                    <?php  if ($otcentro=$sanidad[0]->getOtroCS()=='1') {
                                    echo 'Si';
                                 } else {
                                   echo 'No';
                                 }
                    ?>                                             
              </div>
          </div>
          <div class="form-group col-md-3">
            <strong><h4>Nombre del Centro de Salud</h4></strong>
              <div class="col-sm-3">
                   <?php echo $nomCs=$sanidad[0]->getNomCS(); ?>                                        
              </div>
          </div>
                            <!--Datos del familiar o persona con discapacidad-->
          <div class="form-group col-md-3">
            <strong><h4>¿Tiene algun Familiar con discapacidad?</h4></strong>
              <div class="col-sm-2">
                    <?php  if ($famdisc=$sanidad[0]->getDiscapacidad()=='1') {
                                    echo 'Si';
                                 } else {
                                   echo 'No';
                                 }
                    ?>  
              </div>                                               
          </div> 
        <div class="form-group col-md-3">           
            <strong><h4>Miembro de la Familia</h4></strong>
              <div class="col-sm-3">
                   <?php echo $famdisc=$sanidad[0]->getFamDisc(); ?>                                           
              </div>
        </div>
        <div class="form-group col-md-3">
            <strong><h4>Tipo de Discapacidad</h4></strong>
              <div class="col-sm-3">
                    <?php echo $tipodisc=$sanidad[0]->getTipo(); ?>                                         
              </div>
        </div>
        <div class="form-group col-md-3">
            <strong><h4>¿Posee Certificado unico de Discapacidad</h4></strong>
              <div class="col-sm-2">
                <label class="radio-inline">
                    <?php  if ($certificado=$sanidad[0]->getCertificado()=='1') {
                                    echo 'Si';
                                 } else {
                                   echo 'No';
                                 }
                    ?>                                               
                </label>
              </div> 
          </div>
                            <!--Datos sobre la enfermedad-->
          <div class="form-group col-md-12">
            <strong><h4>Detalles de la Enfermedad</h4></strong>
              <div class="col-sm-12">
                    <?php echo $pdetalle=$sanidad[0]->getDetalles(); ?>                                      
              </div>
          </div>
                  <!--Otras observaciones-->
          <div class="form-group col-md-12">
            <strong><h4>Otras Observaciones</h4></strong>
              <div class="col-sm-12">
                    <?php echo $obser4=$sanidad[0]->getObservacion(); ?>  
              </div>
          </div>
        </div>
                        <!--Vivienda-->
        <div class="tab-pane" id="vivienda1">
                <!--El 1er paso corresponde a los datos principales q otorga el Beneficiario con respecto de la situacion de Habitacional-->

          <div class="form-group col-md-3">
            <strong><h4>Tipo de Tenencia</h4></strong>
              <div class="col-sm-3">
                      <?php $tenencia=$vivienda[0]->getTenencia(); ?> 
                      <?php echo $tenencia->getDescripcion(); ?>                                 
              </div>  
          </div>                            
          <div class="form-group col-md-3">
            <strong><h4>Monto de Alquiler</h4></strong>
              <div class="col-sm-2">
                   <?php echo $montAlq=$vivienda[0]->getMontAlq(); ?>                                     
              </div>
          </div>
          <div class="form-group col-md-3">
            <strong><h4>Propietario</h4></strong>
              <div class="col-sm-2">
                   <?php echo $nomprop=$vivienda[0]->getPropAlq(); ?>                                     
              </div> 
          </div>
          <div class="form-group col-md-3">                  
            <strong><h4>Tiepo de Alquiler</h4></strong>
              <div class="col-sm-2">
                   <?php echo $tiempAlq=$vivienda[0]->getTiemAlq(); ?>                                     
              </div> 
          </div>
          <div class="form-group col-md-3">     
            <strong><h4>Cedida por</h4></strong>
              <div class="col-sm-2">
                   <?php echo $nomCedidor=$vivienda[0]->getCedida(); ?>                                     
              </div>  
          </div>
          <div class="form-group col-md-3"> 
            <strong><h4>Terreno Propio</h4></strong>
              <div class="col-sm-1">
                    <?php  if ($terrprop=$vivienda[0]->getTerrPropio()=='1') {
                                    echo 'Si';
                                 } else {
                                   echo 'No';
                                 }
                    ?>                                         
              </div>
          </div>
          <div class="form-group col-md-3"> 
            <strong><h4>El terreno se encuentra pago</h4></strong>
              <div class="col-sm-1">
                    <?php  if ($terrpag=$vivienda[0]->getTerrPago()=='1') {
                                    echo 'Si';
                                 } else {
                                   echo 'No';
                                 }
                    ?> 
              </div>
          </div>
          <div class="form-group col-md-3"> 
            <strong><h4>Tiene Escritura</h4></strong>
              <div class="col-sm-1">
                    <?php  if ($escritura=$vivienda[0]->getEscritura()=='1') {
                                    echo 'Si';
                                 } else {
                                   echo 'No';
                                 }
                    ?> 
              </div>                          
          </div>            
          <div class="form-group col-md-3"> 
            <strong><h4>¿Posee Automóvil?</h4></strong>
              <div class="col-sm-1">
                    <?php  if ($auto=$vivienda[0]->getAuto()=='1') {
                                    echo 'Si';
                                 } else {
                                   echo 'No';
                                 }
                    ?>                                           
              </div> 
          </div>  
          <div class="form-group col-md-3">  
            <strong><h4>Modelo</h4></strong>
              <div class="col-sm-2">
                   <?php echo $modelo=$vivienda[0]->getModelo(); ?>                                     
              </div> 
          </div>    
          <div class="form-group col-md-3">                   
             <strong><h4>Año</h4></strong>
              <div class="col-sm-2">
                 <?php echo $ano=$vivienda[0]->getAño(); ?>                   
              </div>  
          </div>
          <div class="form-group col-md-3"> 
            <strong><h4>¿Otras propiedades?</h4></strong>
              <div class="col-sm-1">
                    <?php  if ($otprop=$vivienda[0]->getOtraPropiedad()=='1') {
                                    echo 'Si';
                                 } else {
                                   echo 'No';
                                 }
                    ?>                                            
              </div>    
          </div>
          <div class="form-group col-md-12">      
            <strong><h4>Detalle de otros tipo de propiedades</h4></strong>
              <div class="col-sm-12">
                   <?php echo $detallprop=$vivienda[0]->getDetalleprop(); ?>                
              </div>                            
          </div>
                          <!--Datos que corresponde a Ambiente y Mobiliario-->
          <div class="form-group col-md-6">
            <strong><h4>Habitaciones para dormir</h4></strong>
              <div class="col-sm-2">
                 <?php echo $habdormir=$vivienda[0]->getHabitacion(); ?>                   
              </div>
          </div>
          <div class="form-group col-md-3">
            <strong><h4>Piezas en total</h4></strong>
              <div class="col-sm-2">
                 <?php echo $pieza=$vivienda[0]->getPieza(); ?>                  
              </div>                                                              
          </div>                      
          <div class="form-group col-md-3">
            <strong><h4>¿Tiene baño?</h4></strong>
              <div class="col-sm-1">
                    <?php  if ($baño=$vivienda[0]->getBaño()=='1') {
                                    echo 'Si';
                                 } else {
                                   echo 'No';
                                 }
                    ?>                                         
              </div> 
          </div>
          <div class="form-group col-md-4">
            <strong><h4>botón de desague el inodoro</h4></strong>
              <div class="col-sm-1">
                    <?php  if ($boton=$vivienda[0]->getBoton()=='1') {
                                    echo 'Si';
                                 } else {
                                   echo 'No';
                                 }
                    ?>                                         
              </div> 
          </div>
          <div class="form-group col-md-3"> 
            <strong><h4>El Desague es por</h4></strong>
              <div class="col-sm-3">
                      <?php $desague=$vivienda[0]->getDesagote(); ?> 
                      <?php echo $desague->getDescripcion(); ?>                                   
              </div>
          </div>
          <div class="form-group col-md-3">                                          
            <strong><h4>Usado por el Hogar</h4></strong>
              <div class="col-sm-1">
                    <?php  if ($uso=$vivienda[0]->getUso()=='1') {
                                    echo 'Si';
                                 } else {
                                   echo 'No';
                                 }
                    ?>                                         
              </div>
          <div class="form-group col-md-4"> 
            <strong><h4>Estado de Baño</h4></strong>
              <div class="col-sm-2">
                 <?php echo $ubban=$vivienda[0]->getEstado(); ?>                                     
              </div>
          </div>
          <div class="form-group col-md-4">
            <strong><h4>¿Cómo ésta el estado del baño?</h4></strong>
              <div class="col-sm-2">
                 <?php echo $estban=$vivienda[0]->getUbicacion(); ?>                  
              </div> 
          </div>  
          <div class="form-group col-md-3">
            <strong><h4>¿Posee Camas?</h4></strong>
              <div class="col-sm-1">
                    <?php  if ($camas=$vivienda[0]->getCama()=='1') {
                                    echo 'Si';
                                 } else {
                                   echo 'No';
                                 }
                    ?>                                         
              </div> 
          </div>
          <div class="form-group col-md-4">
            <strong><h4>¿Cuantas camas tiene?</h4></strong>
              <div class="col-sm-2">
                 <?php echo $camas1=$vivienda[0]->getCamcant(); ?>                                   
              </div>
          </div>                            
          <div class="form-group col-md-4">
            <strong><h4>¿Mesas y Sillas?</h4></strong>
              <div class="col-sm-1">
                    <?php  if ($mesas=$vivienda[0]->getMesa()=='1') {
                                    echo 'Si';
                                 } else {
                                   echo 'No';
                                 }
                    ?>                                         
              </div> 
          </div>
          <div class="form-group col-md-3">
            <strong><h4>¿Cocina?</h4></strong>
              <div class="col-sm-1">
                    <?php  if ($cocina=$vivienda[0]->getCocina()=='1') {
                                    echo 'Si';
                                 } else {
                                   echo 'No';
                                 }
                    ?>                                         
              </div> 
          </div>
          <div class="form-group col-md-3">
            <strong><h4>¿Heladera?</h4></strong>
              <div class="col-sm-1">
                    <?php  if ($heladera=$vivienda[0]->getHeladera()=='1') {
                                    echo 'Si';
                                 } else {
                                   echo 'No';
                                 }
                    ?>                         
              </div>
          </div> 
          <div class="form-group col-md-12">
            <strong><h4>Observaciones de Ambiente y Mobiliario</h4></strong>
              <div class="col-sm-12">
                <?php echo $obserAmM=$vivienda[0]->getObser1(); ?> 
              </div>
          </div>  
                        <!--Datos corresponde a los servicios basicos de debería tener la vivienda-->
          <div class="form-group col-md-4">
            <strong><h4>Electricidad</h4></strong>
              <div class="col-sm-1">
                    <?php  if ($luz=$vivienda[0]->getLuz()=='1') {
                                    echo 'Si';
                                 } else {
                                   echo 'No';
                                 }
                    ?>                         
              </div>
          </div>
          <div class="form-group col-md-4">
            <strong><h4>¿Por cual medio?</h4></strong>  
              <div class="col-sm-4">
                      <?php $medioluz=$vivienda[0]->getMedio(); ?> 
                      <?php echo $medioluz->getDescripcion(); ?>  
              </div>            
          </div>
          <div class="form-group col-md-3">
            <strong><h4>Agua</h4></strong>
              <div class="col-sm-1">
                    <?php  if ($agua=$vivienda[0]->getAgua()=='1') {
                                    echo 'Si';
                                 } else {
                                   echo 'No';
                                 }
                    ?> 
              </div>
          </div>
          <div class="form-group col-md-4">
            <strong><h4>Es Obtenida por</h4></strong> 
              <div class="col-sm-4">
                      <?php $aguaobt=$vivienda[0]->getObtenida(); ?> 
                      <?php echo $aguaobt->getDescripcion(); ?>  
              </div>
          </div>
          <div class="form-group col-md-4">
            <strong><h4>¿Proviene de?</h4></strong>  
              <div class="col-sm-4">
                      <?php $aguaproveniente=$vivienda[0]->getProveniente(); ?> 
                      <?php echo $aguaproveniente->getDescripcion(); ?> 
              </div>  
          </div>                                            
          <div class="form-group col-md-4">
            <strong><h4>Gas</h4></strong>
              <div class="col-sm-1">
                    <?php  if ($gas=$vivienda[0]->getGas()=='1') {
                                    echo 'Si';
                                 } else {
                                   echo 'No';
                                 }
                    ?>                                           
              </div>
          </div>
          <div class="form-group col-md-4">
            <strong><h4>¿Qué medio utiliza?</h4></strong>   
              <div class="col-sm-4">
                      <?php $gasmedio=$vivienda[0]->getUtiliza(); ?> 
                      <?php echo $gasmedio->getDescripcion(); ?>                                       
              </div>            
          </div>

                  <!--Datos 4to será sobre el tipo de contruccion de la vivienda-->
          <div class="form-group col-md-4">
            <strong><h4>La pared es de</h4></strong> 
              <div class="col-sm-5">
                         
                      <?php $pared=$vivienda[0]->getPared(); ?> 
                     <?php echo $pared->getDescripcion(); ?>          
              </div>                        
          </div>
          <div class="form-group col-md-5">  
            <strong><h4>Material predominante del piso</h4></strong>  
              <div class="col-sm-4">
                      <?php $piso=$vivienda[0]->getPiso(); ?> 
                      <?php echo $piso->getDescripcion(); ?>               
              </div> 
          </div>        
          <div class="form-group col-md-4">                        
            <strong><h4>El techo es de</h4></strong>   
              <div class="col-sm-4">
                      <?php $techo=$vivienda[0]->getTecho(); ?> 
                      <?php echo $techo->getDescripcion(); ?>                 
              </div>
          </div>
          <div class="form-group col-md-4">  
            <strong><h4>El Cielo Razo es de</h4></strong>  
              <div class="col-sm-4">
                      <?php $cielorazo=$vivienda[0]->getCielrazo(); ?> 
                      <?php echo $cielorazo->getDescripcion(); ?>   
              </div>            
          </div>  
          <div class="form-group col-md-12">  
            <strong><h4>Observaciones de la Construcción</h4></strong> 
              <div class="col-sm-12">
                <?php echo $obserc=$vivienda[0]->getObser2(); ?>    
              </div>
          </div>
        </div>




    </div>
  </div>
</div>
                <!--Boton-->
                    <div class="row">
                        <div class="col-sm-6 col-sm-offset-3">
                            <div class="btn-toolbar">
<script type='text/javascript' src='/javascript:windows.print()'></script> 
                              <button class="btn btn-primary btn-label" src="mActionFilePrint.PNG" width=" " alt=""><i class="fa fa-print"></i>Imprimir</button>

                            </div>
                        </div>
                    </div>
        <!--Fin Boton-->