<!--Se modificaran todos los valores del Beneficiario-->
<div class="container">
        <h1>Modificar Beneficiario</h1>
    <div class="col-xs-12">
        <div class="panel panel-midnightblue">
            <div class="panel-heading"><h4>Registro del Beneficiario</h4></div>
                <div class="panel-body">
                    <?php $form->prepare();?>
                        <?php echo $this->form()->openTag($form->setAttributes(['class' => 'form-horizontal', 'data-validate' => 'parsley', 'id' => 'validate-form'])); ?>  
                             <?php $beneficiario=($form->get('beneficiario'));?>
<!--Datos personales-->
                        <div class="form-group">
                            <label class="col-sm-1 control-label">Nombres</label>
                                <div class="col-sm-3">
                                <?php echo $this->formRow($beneficiario->get('nombre')->setAttributes(['placeholder' => 'Ingrese el Nombre completo', 'ata-minlength' => '3', 'required' => 'required', 'class' => 'form-control'])); ?>
                                </div>            
                        </div>
                        <div class="form-group">
                            <label class="col-sm-1 control-label">Apellidos</label>                       
                                <div class="col-sm-3">
                                    <?php echo $this->formRow($beneficiario->get('apellido')->setAttributes(['placeholder' => 'Ingrese el Apellido completo', 'ata-minlength' => '3', 'required' => 'required', 'class' => 'form-control'])); ?>
                                </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-1 control-label">DNI</label>
                              <div class="col-sm-3">
                                <?php echo $this->formRow($beneficiario->get('dni')->setAttributes(['type'=>'text','data-type'=>'digits','required' => 'required', 'class' => 'form-control', 'placeholder'=>'Unicamente numeros'])); ?>
                              </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-1 control-label">Lugar de Nacimiento</label>
                               <div class="col-sm-3">
                               <?php echo $this->formRow($beneficiario->get('lugnac')->setAttributes(['class' => 'form-control','required' => 'required', 'minlength'=>'4'])); ?>
                                </div>

                        <div class="form-group">
                            <label class="col-sm-1 control-label">Fecha de Nacimiento</label>
                                <div class="col-sm-3">
                                <?php echo $this->formRow($beneficiario->get('fechanac')->setAttributes(['required' => 'required', 'class' => 'form-control'])); ?>
                                <div class="input-group date"></div>
                            </div>
                        </div>
                            <div class="form-group">
                                <label class="col-sm-1 control-label">Estado civil </label>
                                    <div class="col-sm-3">
                                        <?php echo $this->formRow($beneficiario->get('estadocivil')->setAttributes(['class' => 'form-control', 'id' => 'source'])); ?>
                                    </div>
                            </div>  
                        </div>
<!--Datos del domicilio de Beneficiario-->
                <div class="form-group">
                    <label class="col-sm-1 control-label">Domicilio</label>
                        <div class="col-sm-3">
                            <?php echo $this->formRow($beneficiario->get('domben')->setAttributes(['class' => 'form-control','required' => 'required', 'minlength'=>'3'])); ?>
                         </div>
                    <label class="col-sm-1 control-label">Ciudad</label>
                        <div class="col-sm-2">
                        <?php echo $this->formRow($beneficiario->get('ciudad')->setAttributes(['placeholder' => 'Ciudad','required' => 'required','class' => 'form-control', 'minlength'=>'4'])); ?>
                        </div>
                    <label class="col-sm-1 control-label">Provincia</label>
                        <div class="col-sm-2">
                        <?php echo $this->formRow($beneficiario->get('provincia')->setAttributes(['placeholder' => 'Provincia','required' => 'required','class' => 'form-control', 'minlength'=>'4'])); ?>
                        </div>       
                </div> 
                <div class="form-group">
                    <label class="col-sm-1 control-label">Residencia en Catriel</label>
                        <div class="col-sm-3">
                            <?php echo $this->formRow($beneficiario->get('resben')->setAttributes(['class' => 'form-control','required' => 'required', 'minlength'=>'4'])); ?>
                        </div>
                </div>
                <div class="form-group">     
                    <label  class="col-sm-1 control-label">Telefono</label>
                        <div class="col-sm-3">   
                            <?php echo $this->formRow($beneficiario->get('telfben')->setAttributes(['class' => 'form-control mask', 'minlength'=>'4', 'data-inputmask'=>'mask:(0000) 000-0000' ])); ?>
                                <p class="help-block">(0000) 000-0000</p>
                        </div>

                </div>
<!--Datos de Estudio y Oficio del Beneficiario-->
                <div class="form-group">
                    <label class="col-sm-1 control-label">Tipo de Estudios</label>
                        <div class="col-sm-3">
                            <?php echo $this->formRow($beneficiario->get('educacion')->setAttributes(['class' => 'form-control', 'id' => 'source'])); ?>
                        </div> 
                </div> 
                <div class="form-group">
                    <label class="col-sm-1 control-label">Oficio</label>
                        <div class="col-sm-3">
                            <?php echo $this->formRow($beneficiario->get('profession')->setAttributes(['class' => 'form-control', 'id' => 'source'])); ?>
                       </div> 
                </div>
<!--Inicia del boton-->
                <div class="panel-footer">
                    <div class="row">
                        <div class="col-sm-6 col-sm-offset-3">
                            <div class="btn-toolbar">
                                <button type="submit" class="btn-primary btn" >Guardar Cambios</button>
                            </div>
                        </div>
                    </div>
                    <?php echo $this->form()->closeTag(); ?> 
                </div>
<!--Finaliza Boton-->
            </div>
        </div>
</div>