<?php include 'cabecera.php' ?>
<div class="row">
    <div class="panel panel-info">
                                <div class="panel-heading">
                                    <h4>Alta Beneficiario</h4>
                                </div>
        <div class="panel-body">
                <p>Este formulario consiste en los datos personales del beneficiario. Los datos se deben completar en su totalidad</p>
            <div class="tab-content">
                <div class="tab-pane active" id="domwizard">
                    <?php $form->prepare();?>
                        <?php echo $this->form()->openTag($form->setAttributes(['class' => 'form-horizontal', 'id' => 'wizard'])); ?>  
                            <?php $beneficiario=($form->get('beneficiario'));?>

<!--El primer paso corresponde a los datos principales del Beneficiario y llega hasta Estado Civil-->
    <fieldset title="Paso 1">
        <legend>Datos Personales</legend>
            <div class="form-group">
                <label for="fieldname" class="col-md-1 control-label">Nombres</label>
                    <div class="col-md-3">
                        <?php echo $this->formRow($beneficiario->get('nombre')->setAttributes(['placeholder' => 'Nombre Completo','required' => 'required','class' => 'form-control', 'minlength'=>'4' ])); ?>
                    </div>
                <label for="fieldemail" class="col-md-1 control-label">Apellidos</label>
                    <div class="col-md-3">
                        <?php echo $this->formRow($beneficiario->get('apellido')->setAttributes(['placeholder' => 'Apellido Completo','required' => 'required','class' => 'form-control'])); ?>
                    </div>                   
                <label for="fieldname" class="col-md-1 control-label">DNI</label>
                    <div class="col-md-3">
                        <?php echo $this->formRow($beneficiario->get('dni')->setAttributes(['placeholder' => 'DNI (sin guion o punto)','required' => 'required','class' => 'form-control', 'minlength'=>'4'])); ?>
                    </div>                    
            </div>

            <div class="form-group">
                <label for="fieldname" class="col-md-1 control-label">Lugar de Nacimiento</label>
                    <div class="col-md-3">
                        <?php echo $this->formRow($beneficiario->get('lugnac')->setAttributes(['placeholder' => 'Lugar de Nacimiento','required' => 'required','class' => 'form-control', 'minlength'=>'4'])); ?>
                    </div>
                <label class="col-sm-1 control-label">Fecha de Nacimiento</label>
                    <div class="col-sm-3">
                        <?php echo $this->formRow($beneficiario->get('fechanac')->setAttributes(['required' => 'required','class' => 'form-control'])); ?>
                            <div class="input-group date"></div>                     
                    </div>
            <div class="form-group">
                <label class="col-sm-1 control-label">Estado civil</label>
                    <div class="col-sm-3">
                        <?php echo $this->formRow($beneficiario->get('estadocivil')->setAttributes(['required' => 'required','class' => 'form-control', 'id' => 'source'])); ?>
                   </div>                    
            </div> 
    </fieldset>
<!--E 2do paso es corresponde a los Datos de Domicilo, Donde vive y hace cuanto reside el Beneficiario-->
    <fieldset title="Paso 2">
        <legend>Domicilio</legend>
            <div class="form-group">
                <label for="fieldname" class="col-md-1 control-label">Domicilio</label> 
                    <div class="col-md-3">
                        <?php echo $this->formRow($beneficiario->get('domben')->setAttributes(['placeholder' => 'Domicilio','required' => 'required','class' => 'form-control', 'minlength'=>'4'])); ?>
                    </div>
                <label class="col-sm-1 control-label">Ciudad</label>
                    <div class="col-sm-3">
                        <select id="e1" style="width:100%" class="populate">
                                <option value="AK">Alaska</option>
                                <option value="HI">Hawaii</option>
                                <option value="CA">California</option>
                                <option value="NV">Nevada</option>
                                <option value="OR">Oregon</option>
                                <option value="WA">Washington</option>
                        </select>
                    </div>
                <label class="col-sm-1 control-label">Provincia</label>
                    <div class="col-sm-3">
                        <select id="e2" style="width:100%" class="populate">
                                <option value="AK">Alaska</option>
                                <option value="HI">Hawaii</option>
                                <option value="CA">California</option>
                                <option value="NV">Nevada</option>
                                <option value="OR">Oregon</option>
                                <option value="WA">Washington</option>
                        </select>
                    </div>       
            </div> 
            <div class="form-group">
                <label for="fieldname" class="col-md-1 control-label">Residencia en Catriel</label>
                    <div class="col-md-3">
                        <?php echo $this->formRow($beneficiario->get('resben')->setAttributes(['placeholder' => 'Tiempo de Residencia en Catriel','required' => 'required','class' => 'form-control', 'minlength'=>'4'])); ?>
                    </div>
                <label for="fieldname" class="col-md-1 control-label">Telefono</label>
                    <div class="col-md-3">                       
                        <?php echo $this->formRow($beneficiario->get('telfben')->setAttributes(['required' => 'required', 'class' => 'form-control mask', 'minlength'=>'4', 'data-inputmask'=>'mask:(0000) 000-0000' ])); ?>
                       <p class="help-block">(0000) 000-0000</p>
                    </div>
            </div>
    </fieldset>
<!--El 3er paso consiste en saber sobre la Educacion y el Oficio del Beneficiario-->
    <fieldset title="Paso 3">
        <legend>Educación y Oficio</legend>
            <div class="form-group">
                <label class="col-sm-1 control-label">Tipo de Estudios</label>
                    <div class="col-sm-3">
                        <?php echo $this->formRow($beneficiario->get('educacion')->setAttributes(['required' => 'required', 'class' => 'form-control'])); ?>
                   </div> 
            </div> 
            <div class="form-group">
                <label class="col-sm-1 control-label">Oficio</label>
                    <div class="col-sm-3">
                        <?php echo $this->formRow($beneficiario->get('profession')->setAttributes(['required' => 'required', 'class' => 'form-control'])); ?>
                   </div> 
            </div>
           
    </fieldset> 
        <div class="col-sm-6 col-sm-offset-3">
            <div class="btn-toolbar">
                <button type="submit" class="finish btn-success btn" value="Submit" />Registrar</button>
            </div>
        </div>
           <?php echo $this->form()->closeTag(); ?> 
<!--
            <?php //echo $this->formSubmit($form->get('submit')->setAttributes(['class' => 'finish btn-success btn'])); ?>-->
            <!--<input type="submit" class="finish btn-success btn" value="Submit" />-->

      
                </div>   
            </div>     
        </div>
    </div>
</div>