<div class="col-md-12">
  <div class="panel panel-sky">
    <h1>Beneficiarios</h1>
  
      <div class="panel-heading">
          <h4>Lista de Beneficiarios</h4>
          <div class="options">
              <a href="javascript:;" class="panel-collapse"><i class="fa fa-chevron-down"></i></a>
          </div>
      </div>
      <div class="panel-body collapse in">
          <?php echo $this->flashMessenger()->render('success', array('alert', 'alert-dismissable', 'alert-success')); ?>
          <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered datatables" id="example">
              <thead>
                  <tr>
                        <th>Nro Legajo</th>
                        <th>Nombre</th>
                        <th>Apellido</th>                                    
                        <th>DNI</th>
                        <th>Domicilio</th>
                        <th>Telefono</th>
                        <th>MÁS</th>

                    </tr>
                </thead>
                <tbody>
                <?php foreach ($beneficiarios as $beneficiario): ?>
                    <tr class="odd gradeX">
                      <td>
                        <?php echo $beneficiario->getIdBeneficiario() ?>
                      </td>
                      <td>
                        <?php echo $beneficiario->getNombre() ?>
                      </td>
                      <td>
                        <?php echo $beneficiario->getApellido() ?>
                      </td>

                      <td>
                        <?php echo $beneficiario->getDni() ?>
                      </td>
                      <td>
                        <?php echo $beneficiario->getDomben() ?>
                      </td>
                      <td>
                        <?php echo $beneficiario->getTelfben() ?>
                      </td>
                      <td>
                      <div class="btn-group">
                              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                Más <span class="caret"></span>
                              </button>
                              <ul class="dropdown-menu" role="menu">
                                <!--Opcion uno se dirige a Ingresar Nuevo Familiar-->
                                <li><a  href="<?php echo $this->url('nuevoFam', array('id' => $beneficiario->getIdBeneficiario())) ?>"><i class="fa fa-group"></i>Familia</a></li>

                      <!--Opcion dos se dirige a Ingresar la Situacion Habitacional-->                          
                                <li><a  href="#"><i class="fa fa-home"></i>Habitacional</a></li>

                      <!--Opcion tres se dirige a Ingresar la Situacion Economica-->
                                <li><a href="#"><i class="fa fa-briefcase"></i>Económica</a></li>

                      <!--Opcion cuatro se dirige a Ingresar la Situacion Sanidad-->
                                <li><a href="<?php echo $this->url('nuevoS', array('id' => $beneficiario->getIdBeneficiario())) ?>"><i class="fa fa-h-square"></i>Sanidad</a></li>
                               
                                <li class="divider"></li>
                       <!--Opcion cinco se dirige a Modificar Beneficiario-->
                                <li><a href="<?php echo $this->url('modbeneficiario', array('id' => $beneficiario->getIdBeneficiario())) ?>"><i class="fa fa-cog"></i>Modificar</a></li>
                        <!--Opcion cinco se dirige a Eliminar Beneficiario-->
                                <li><a href="<?php echo $this->url('del-beneficiario', array('id' => $beneficiario->getIdBeneficiario())) ?>"><i class="fa fa-times"></i>Eliminar</a></li>
                                
                              </ul>
                            </div>
                      </td>
                    </tr>

                <?php endforeach; ?>
              </tbody>
          </table><!--end table-->
      </div>
  </div>
</div>