<div class="col-md-12">
  <div class="panel panel-sky">
    <h1>Empleado</h1>
  
      <div class="panel-heading">
          <h4>Lista empleados</h4>
          <div class="options">
              <a href="javascript:;" class="panel-collapse"><i class="fa fa-chevron-down"></i></a>
          </div>
      </div>
      <div class="panel-body collapse in">
          <?php echo $this->flashMessenger()->render('success', array('alert', 'alert-dismissable', 'alert-success')); ?>
          <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered datatables" id="example">
              <thead>
                  <tr>
                        <th>Nro Legajo</th>
                        <th>Nombre</th>
                        <th>Apellido</th>                                    
                        <th>DNI</th>
                        <th>Domicilio</th>
                        <th>Telefono</th>
                        <th>MÁS</th>
                        <th>Modificar</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($beneficiarios as $beneficiario): ?>
                    <tr class="odd gradeX">
                      <td>
                        <?php echo $beneficiario->getIdBeneficiario() ?>
                      </td>
                      <td>
                        <?php echo $beneficiario->getNombre() ?>
                      </td>
                      <td>
                        <?php echo $beneficiario->getApellido() ?>
                      </td>

                      <td>
                        <?php echo $beneficiario->getDni() ?>
                      </td>
                      <td>
                        <?php echo $beneficiario->getDomben() ?>
                      </td>
                      <td>
                        <?php echo $beneficiario->getTelfben() ?>
                      </td>
                      <td>
                        <a class="btn btn-warning-alt btn-label" href="<?php echo $this->url('nevoFam', array('id' => $beneficiario->getIdBeneficiario())) ?>"></i>Familia</a> 
                      </td>
                      <td>
                      <a class="btn btn-warning-alt btn-label" href="<?php echo $this->url('modbeneficiario', array(
                      'id' => $beneficiario->getIdBeneficiario())) ?>"><i class="fa fa-cog"></i>Modificar</a>     
                        <a class="btn btn-danger-alt btn-label" href="<?php echo $this->url('del-beneficiario', 
                                array('id' => $beneficiario->getIdBeneficiario())) ?>"><i class="fa fa-times"></i>Eliminar</a>


                      </td>
                    </tr>

                <?php endforeach; ?>
              </tbody>
          </table><!--end table-->
      </div>
  </div>
</div>