<div class="col-md-12">
  <div class="panel panel-sky">
    <h1>Familias</h1>
  
      <div class="panel-heading">
          <h4>Lista de Familias</h4>
          <div class="options">
              <a href="javascript:;" class="panel-collapse"><i class="fa fa-chevron-down"></i></a>
          </div>
      </div>
      <div class="panel-body collapse in">
          <?php echo $this->flashMessenger()->render('success', array('alert', 'alert-dismissable', 'alert-success')); ?>
          <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered datatables" id="example">
              <thead>
                  <tr>
                        <th>Nro Legajo</th>
                        <th>Nombre</th>
                        <th>Apellido</th>                                    
                        <th>DNI</th>
                        <th>Relacion</th>
                        <th>Beneficiario</th>
                        <th>MÁS</th>

                    </tr>
                </thead>
                <tbody>
                <?php foreach ($famlias as $familia): ?>
                    <tr class="odd gradeX">
                      <td>
                        <?php echo $familia->getNroF() ?>
                      </td>
                      <td>
                        <?php echo $familia->getNombre() ?>
                      </td>
                      <td>
                        <?php echo $familia->getApellido() ?>
                      </td>

                      <td>
                        <?php echo $familia->getDni() ?>
                      </td>
                      <td>
                        <?php echo $familia->getRelacion() ?>
                      </td>
                      <td>
                        <?php echo $familia->getIdben() ?>
                      </td>
                      <td>
                        <a class="btn btn-warning-alt btn-label" href="<?php echo $this->url('modFam', array('id' => $familia->getNroF())) ?>"><i class="fa fa-cog"></i>Modificar</a>     
                        <a class="btn btn-danger-alt btn-label" href="<?php echo $this->url('delFam', array('id' => $familia->getNroF())) ?>"><i class="fa fa-times"></i>Eliminar</a>
                      </td>
                    </tr>

                <?php endforeach; ?>
              </tbody>
          </table><!--end table-->
      </div>
  </div>
</div>