<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Politica Social</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="Politica Social">
	<meta name="author" content="The Red Team">


    <link rel="stylesheet" href="/css/styles.css?=140">
    <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600' rel='stylesheet' type='text/css'>

    <link href='/demo/variations/default.css' rel='stylesheet' type='text/css' media='all' id='styleswitcher'> 
    <link href='/demo/variations/default.css' rel='stylesheet' type='text/css' media='all' id='headerswitcher'>

    <!--+++++Harry Hernandez ++++++-->
    <link rel='stylesheet' type='text/css' href='/plugins/datatables/dataTables.css' /> 
    <!--++++++++++++++++++++++++-->
 
    <link rel='stylesheet' type='text/css' href='/plugins/form-daterangepicker/daterangepicker-bs3.css' /> 
    <link rel='stylesheet' type='text/css' href='/plugins/fullcalendar/fullcalendar.css' /> 
    <link rel='stylesheet' type='text/css' href='/plugins/form-markdown/css/bootstrap-markdown.min.css' /> 
    <link rel='stylesheet' type='text/css' href='/plugins/codeprettifier/prettify.css' /> 
    <link rel='stylesheet' type='text/css' href='/plugins/form-toggle/toggles.css' />



</head>

<body class="">

<header class="navbar navbar-inverse navbar-fixed-top" role="banner">
        <a id="leftmenu-trigger" class="tooltips" data-toggle="tooltip" data-placement="right" title="Toggle Sidebar"></a>
        <div class="navbar-header pull-left">
            <a class="navbar-brand" href="index.htm">Politica Social</a>
        </div>

        <ul class="nav navbar-nav pull-right toolbar">
            <li class="dropdown">
                <?php $sector = $this->empleado->getSector();
                   $sector->getNombre();
                ?>
                <?php if (!$this->empleado): ?>                
                    <a href="<?php echo $this->url('login') ?>" class="dropdown-toggle username" >Iniciar sesión</a>
                <?php else: ?>
                    <a href="#" class="dropdown-toggle username" data-toggle="dropdown"><span class="hidden-xs"><?php echo $this->empleado->getNombre() ?>  <i class="fa fa-caret-down"></i></span></a>
                <?php endif; ?>
                <ul class="dropdown-menu userinfo arrow">
                    <li class="userlinks">
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->url('logout') ?>" class="text-right">Cerrar sesión</a></li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
    </header>
<!--Todo esto pertenece al menu vertical-->
    <div id="page-container">
        <!-- BEGIN SIDEBAR -->
        <nav id="page-leftbar" role="navigation">
                <!-- BEGIN SIDEBAR MENU -->
            <ul class="acc-menu" id="sidebar">
                <li class="divider"></li>
                <li><a href="<?php echo $this->url('home') ?>"></i> <span>Inicio</span></a></li>          
                <li><a href="javascript:;"><i class="fa fa-group"></i> <span>Tramites Beneficiario</span></a>
                    <ul class="acc-menu">
                        <li><a href="javascript:;">Beneficiario</a>
                            <ul class="acc-menu">
                                <li><a href="<?php echo $this->url('nuevo-beneficiario') ?>">Alta Beneficiario</a></li>
                                <li><a href="<?php echo $this->url('ver-beneficiario') ?>">Registros de Beneficiarios</a></li>
                            </ul>
                        </li>
                        <li><a href="<?php echo $this->url('verFam') ?>">Registros Familias</a></li>
                        <li><a href="<?php echo $this->url('ver_S') ?>">Registros de Sanidad</a></li>
                        <li><a href="<?php echo $this->url('verE') ?>">Registros de Económia</a></li>
                        <li><a href="<?php echo $this->url('verviv') ?>">Registros de Vivienda</a></li>                        
                    </ul>
                    <!--Falta la asistencia y borre el buscador-->
                </li> 
                <li><a href="javascript:;"><i class="fa fa-user"></i> <span>Empleado</span></a>
                    <ul class="acc-menu">
                        <li><a href="<?php echo $this->url('index_empleado') ?>">Lista de empleados</a></li>
                        <li><a href="<?php echo $this->url('nuevo_empleado') ?>">Nuevo empleado</a></li>
                    </ul>
                </li>
                <li><a href="javascript:;"><i class="fa fa-qrcode"></i> <span>Sector</span></a>
                    <ul class="acc-menu">
                        <li><a href="<?php echo $this->url('index_sector') ?>">Lista de sectores</a></li>
                        <li><a href="<?php echo $this->url('nuevo_sector') ?>">Nuevo sector</a></li>
                    </ul>
                </li>
            </ul>
            <!-- END SIDEBAR MENU -->
            <!-- El nav final es el que mantiene la estructura del menu vertical -->
        </nav>


        <div id="page-content">
    		<div class="container">
                 <?php echo $this->content; ?>
    		</div> <!-- container -->
        </div> <!-- page-content -->

        <footer role="contentinfo">
            <div class="clearfix">
                <ul class="list-unstyled list-inline pull-left">
                    <li>ISNU &copy; 2015</li>
                </ul>
                <button class="pull-right btn btn-inverse-alt btn-xs hidden-print" id="back-to-top"><i class="fa fa-arrow-up"></i></button>
            </div>
        </footer>

    </div> <!-- page-container -->

<!--Script propios de la plantilla Avant-->

<script type='text/javascript' src='/js/jquery-1.10.2.min.js'></script> 
<script type='text/javascript' src='/js/jqueryui-1.10.3.min.js'></script> 
<script type='text/javascript' src='/js/bootstrap.min.js'></script> 
<script type='text/javascript' src='/js/enquire.js'></script> 
<script type='text/javascript' src='/js/jquery.cookie.js'></script> 
<script type='text/javascript' src='/js/jquery.nicescroll.min.js'></script> 
<script type='text/javascript' src='/plugins/codeprettifier/prettify.js'></script> 
<script type='text/javascript' src='/plugins/easypiechart/jquery.easypiechart.min.js'></script> 
<script type='text/javascript' src='/plugins/sparklines/jquery.sparklines.min.js'></script> 
<script type='text/javascript' src='/plugins/form-toggle/toggle.min.js'></script> 
<script type='text/javascript' src='/js/placeholdr.js'></script> 
<script type='text/javascript' src='/js/application.js'></script> 
<script type='text/javascript' src='/demo/demo.js'></script> 
<script type='text/javascript' src='/plugins/fullcalendar/fullcalendar.min.js'></script> <!--10/12/15-->
<!--++++Harry Hernandez 12-11-15++++++++-->
<script type='text/javascript' src='/plugins/datatables/jquery.dataTables.min.js'></script> 
<script type='text/javascript' src='/plugins/datatables/dataTables.bootstrap.js'></script> 
<script type='text/javascript' src='/demo/demo-datatables.js'></script> 
<!--++++++++++++++++++++++++++++-->



<!--Esto supuestamente es para el formulario Wizard para que funcione el STEP-->

<script type='text/javascript' src='/plugins/form-validation/jquery.validate.min.js'></script> 
<script type='text/javascript' src='/plugins/form-stepy/jquery.stepy.js'></script>

<!--Esto supuestamente es para el formulario o cualquier lugar para que funcione el select de multifuncion-->

<script type='text/javascript' src='/plugins/form-multiselect/js/jquery.multi-select.min.js'></script> 
<script type='text/javascript' src='/plugins/quicksearch/jquery.quicksearch.min.js'></script> 
<script type='text/javascript' src='/plugins/form-typeahead/typeahead.min.js'></script> 
<script type='text/javascript' src='/plugins/form-select2/select2.min.js'></script> 

<!--Esto es para que funcione el calendario en el formulario y cualquier parte en que este-->

<script type='text/javascript' src='/plugins/form-autosize/jquery.autosize-min.js'></script> 
<script type='text/javascript' src='/plugins/form-colorpicker/js/bootstrap-colorpicker.min.js'></script> 
<script type='text/javascript' src='/plugins/jqueryui-timepicker/jquery.ui.timepicker.min.js'></script> 
<script type='text/javascript' src='/plugins/form-daterangepicker/daterangepicker.min.js'></script> 
<script type='text/javascript' src='/plugins/form-datepicker/js/bootstrap-datepicker.js'></script> 
<script type='text/javascript' src='/plugins/form-daterangepicker/moment.min.js'></script> 
<script type='text/javascript' src='/plugins/form-fseditor/jquery.fseditor-min.js'></script> 






</body>
</html>