            
    <div class="container">
        <h1>Sector</h1>

                  <div class="col-md-12">
                    <div class="panel panel-indigo">
                        <div class="panel-heading">
                            <h4>Lista sectores</h4>
                            <div class="options">
                                <a href="javascript:;" class="panel-collapse"><i class="fa fa-chevron-down"></i></a>
                            </div>
                        </div>
                        <div class="panel-body collapse in">
                            <?php echo $this->flashMessenger()->render('success', array('alert', 'alert-dismissable', 'alert-success')); ?>
                            <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered datatables" id="editable">
                                <thead>
                                    <tr>
                                        <th>Id Sector</th>
                                        <th>Nombre</th>                                        
                                    </tr>
                                </thead>
                                <tbody>
                              <?php foreach ($sectores as $sector): ?>
                                    <tr class="even gradeC"> <td>
                                        <?php echo $sector->getId() ?>
                                      </td>
                                      <td>
                                        <?php echo $sector->getNombre() ?>
                                      </td>
                                      <td>
                                          <a class="btn btn-warning-alt btn-label" href="<?php echo $this->url('editar_sector', array(
                                        'id' => $sector->getId())) ?>"><i class="fa fa-cog"></i>Editar</a>  
                                  
                                          <a class="btn btn-danger-alt btn-label" href="<?php echo $this->url('eliminar_sector', 
                                                  array('id' => $sector->getId())) ?>"><i class="fa fa-times"></i>Eliminar</a>                                          
                                     </td>
                                    </tr>
                                    <?php endforeach; ?>
                                    
                                </tbody>
                            </table><!--end table-->
                        </div>
                    </div>
                </div>
    </div>
