<div class="col-md-12">
  <div class="panel panel-sky">
    <h1>Empleado</h1>
  
      <div class="panel-heading">
          <h4>Lista empleados</h4>
          <div class="options">
              <a href="javascript:;" class="panel-collapse"><i class="fa fa-chevron-down"></i></a>
          </div>
      </div>
      <div class="panel-body collapse in">
          <?php echo $this->flashMessenger()->render('success', array('alert', 'alert-dismissable', 'alert-success')); ?>
          <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered datatables" id="example">
              <thead>
                  <tr>
                      <th>Id Stock</th>
                      <th>Catindad</th>
                      <th>Unidad</th>
                      <th>Fecha de ingreso</th>
                  </tr>
              </thead>
              <tbody>
                
                <?php foreach ($stocks as $stock): ?>
                  
                  <tr class="even gradeC"> 
                    <td>
                      <?php echo $stock->getIdStock() ?>
                    </td>
                    <td>
                      <?php echo $stock->getCantidad() ?>
                    </td>
                    <td>
                      <?php echo $stock->getUnidad() ?>
                    </td>
                    <td>
                        <?php  $fechaIngreso  =$stock->getFechaDeIngreso()  ?>
                        <?php echo $fechaIngreso->format('d-m-Y')  ?>            
                    </td>
                    
                  </tr>
                <?php endforeach; ?>
                  
              </tbody>
          </table><!--end table-->
      </div>
  </div>
</div>