<div class="container">
            <div class="row">
              <div class="col-md-12">
                    <div class="panel panel-sky">
                        <div class="panel-heading">
                            <h4>Lista de productos</h4>
                            <div class="options">   
                                <a href="javascript:;"><i class="fa fa-cog"></i></a>
                                <a href="javascript:;"><i class="fa fa-wrench"></i></a>
                                <a href="javascript:;" class="panel-collapse"><i class="fa fa-chevron-down"></i></a>
                            </div>
                        </div>
                        <div class="panel-body collapse in">
                            <?php echo $this->flashMessenger()->render('success', array('alert','alert-dismissable', 'alert-success')); ?>
                            <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered datatables" id="editable">
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Ítem</th>
                                        <th>Descripción</th>
                                        <th>Fecha ingreso</th>
                                        <th>Operaciones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach($productos as $producto): ?>
                                        <tr class="odd gradeX">
                                            <td><?php echo $producto->getIdProducto() ?></td>
                                            <td><?php echo $producto->getItem() ?></td>                                            
                                            <td><?php echo $producto->getDescripcion() ?></td>
                                            <?php  $fechaIngreso  =$producto->getFechaIngreso()  ?>
                                            <td><?php echo $fechaIngreso->format('d-m-Y')  ?></td>
                                            <td>
                                                <a class="btn btn-warning-alt btn-label" href="<?php echo $this->url('editar_producto', array(
                                                'id' => $producto->getIdProducto()))?>">
                                                    <i class="fa fa-cog"></i>Editar</a>     
                                                    <a class="btn btn-danger-alt btn-label" href="<?php echo $this->url('eliminar_producto', array(
                                                'id' => $producto->getIdProducto()))?>">
                                                        <i class="fa fa-times"></i>Eliminar</a>
                                            </td>
                                           </tr>
                                     <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div> <!-- container -->