<?php //include 'encabezado.php'; ?>

<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h4>Nuevo Producto</h4>

            </div>
            <div class="panel-body">
                <h3>Producto</h3>
                <p>Ingrese los datos del nuevo producto</p>
                <p class="text-primary">El ID de producto, stock se genera automáticamente y fecha de ingreso es por defecto la actual.</p>
                <br>
                <?php $form->prepare() ?>
                <?php echo $this->form()->openTag($form->setAttributes(['class' => 'form-horizontal row-border', 'data-validate' => 'parsley', 'id' => 'validate-form'])) ?>
                <?php //var_dump($form);die;
                $producto = $form->get('producto');             
                ?>

                <div class="form-group">
                    <label for="focusedinput" class="col-sm-3 control-label">Nombre del producto</label>
                    <div class="col-sm-6">

                        <?php echo $this->formRow($producto->get('nombre')->setAttributes(['placeholder' => 'Ingrese el nombre del item', 'id' => 'focusedinput', 'ata-minlength' => '2',
                                    'required' => 'required', 'class' => 'form-control', 'type' => 'text'])); ?> 
                    </div>
                </div>

                <div class="form-group">
                    <label for="txtarea1" class="col-sm-3 control-label">Descripción</label>
                    <div class="col-sm-6"><?php echo $this->formRow($producto->get('descripcion')->setAttributes(['placeholder' => 'Ingrese  la descripcion', 'ata-minlength' => '2', 'required' => 'required',
                                    'class' => 'form-control']));?></div>
                 
                </div>      

                <div class="form-group">
                        <label class="col-sm-3 control-label">
                            Cantidad
                        </label>
                        <div class="col-sm-6">
                            <?php echo $this->formRow($producto->get('cantidad')->setAttributes(['type'=>'text','data-type'=>'digits','required' => 'required', 'class' => 'form-control', 'placeholder'=>'Unicamente numeros'])); ?>
                        </div>
                </div>

                <div class="form-group">
                        <label class="col-sm-3 control-label">
                            Stock Critico
                        </label>
                        <div class="col-sm-6">
                            <?php echo $this->formRow($producto->get('stockCritico')->setAttributes(['type'=>'text','data-type'=>'digits','required' => 'required', 'class' => 'form-control', 'placeholder'=>'Unicamente numeros'])); ?>
                        </div>
                </div>
                
		  

            </div>
            <div class="panel-footer">
                <div class="row">
                    <div class="col-sm-6 col-sm-offset-3">
                        <div class="btn-toolbar">
                            <button type="submit" class="btn-primary btn">Registrar</button>

                        </div>
                    </div>
                </div>
            </div>
            
<?php echo $this->form()->closeTag(); ?> 
        </div>
    </div>
</div>
<?php include 'footer.php'; ?>
