<div class="col-md-12">
  <div class="panel panel-sky">
    <h1>Situación Habitacional</h1>
  
      <div class="panel-heading">
          <h4>Registros de Situación de Habitacional de los Beneficiarios</h4>
          <div class="options">
              <a href="javascript:;" class="panel-collapse"><i class="fa fa-chevron-down"></i></a>
          </div>
      </div>
      <div class="panel-body collapse in">
          <?php echo $this->flashMessenger()->render('success', array('alert', 'alert-dismissable', 'alert-success')); ?>
          <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered datatables" id="example">
              <thead>
                  <tr>
                        <th>Nro Registro</th>
                        <th>Beneficiario</th>
                        <th>Tipo de Tenencia</th>                                    
                        <th>Posee Auto</th>
                        <th>Otras Propiedades</th>
                        <th>Observación de otras propiedades</th>
                        <th>Observación Ambiente y Moviliario</th>
                        <th>Servicio de Luz</th>
                        <th>Servicio de Agua</th>
                        <th>Servicio de Gas</th>                                                
                        <th>Observación de la Construcción</th>


                    </tr>
                </thead>
                <tbody>
                <?php foreach ($viviendas as $vivienda): ?>
                    <tr class="odd gradeX">
                      <td>
                        <?php echo $vivienda->getIdVivienda() ?>
                           <div class="btn-group">
                              <button type="button" class="btn btn-default dropdown-toggle btn btn-default btn-xs" data-toggle="dropdown">
                               <i class="fa fa-plus"> </i><span class="caret"></span>
                              </button>
                              <ul class="dropdown-menu" role="menu">
                                <!--Opcion uno se dirige a a la vista de Beneficiario-->
                                <li><a  href="<?php echo $this->url('ver-beneficiario')?>"><i class="fa fa-user"></i>Ver Beneficiarios</a></li>
                               <li class="divider"></li>
                       <!--Opcion cinco se dirige a Modificar Vivienda-->
                                <li><a href="<?php echo $this->url('modviv', array('id' => $vivienda->getIdVivienda())) ?>"><i class="fa fa-cog"></i>Modificar</a></li>
                        <!--Opcion cinco se dirige a Eliminar Vivienda-->
                                <li><a href="<?php echo $this->url('delviv', array('id' => $vivienda->getIdVivienda())) ?>"><i class="fa fa-times"></i>Eliminar</a></li>
                                
                              </ul>
                            </div>                        
                      </td>
                      <td>
                      <?php $beneficiario = $vivienda->getIdben() ?>  
                        <?php echo $beneficiario->getNombre(); echo "  "; echo $beneficiario->getApellido()?>
                      </td>
                      <td>
                      <!--Tipo de Tenencia-->
                      <?php  $tenencia = $vivienda->getTenencia() ?>  
                        <?php echo $tenencia->getDescripcion() ?>
                      </td>
                      <td>
                      <!--Booleano de Auto-->
                        <?php echo $vivienda->getAuto() ?>
                      </td>

                      <td>
                      <!--Booleano Otras propiedades-->
                        <?php echo $vivienda->getOtraPropiedad() ?>
                      </td>
                      <!--Observacion de otras propiedades-->
                      <td>
                        <?php echo $vivienda->getDetalleprop() ?>
                      </td>                       
                      <td>
                      <!--Observacion de Ambiente y Muebles-->
                        <?php echo $vivienda->getObser1() ?>
                      </td>
                      <!--booleano de Luz-->                      
                      <td>
                        <?php echo $vivienda->getLuz() ?>
                      </td>                      
                     <!--booleanode Agua-->
                      <td>
                        <?php echo $vivienda->getAgua() ?>
                      </td>
                      <!--booleano de Gas-->
                      <td>
                        <?php echo $vivienda->getGas() ?>
                      </td>
                      <!--Observacion sobre el estado de la construccion-->
                      <td>
                        <?php echo $vivienda->getObser2() ?>
                      </td>                                            

                    </tr>

                <?php endforeach; ?>
              </tbody>
          </table><!--end table-->
      </div>
  </div>
</div>