<!--Se modificaran todos los valores del Familiar-->
<div class="container">
        <h1>Modificar Registro de Sanidad</h1>
    <div class="col-xs-12">
        <div class="panel panel-midnightblue">
            <div class="panel-heading"><h4>Registro de Sanidad del Beneficiario</h4></div>
                <div class="panel-body">
                    <?php $form->prepare();?>
                        <?php echo $this->form()->openTag($form->setAttributes(['class' => 'form-horizontal', 'data-validate' => 'parsley', 'id' => 'validate-form'])); ?>  
                             <?php $sanidad=($form->get('sanidad'));?>
<!--Datos de la cobertura social-->
                        <div class="form-group">
                            <label class="col-sm-1 control-label">Cobertura de Obra Social</label>
                                <div class="col-sx-1">
                                    <label class="radio-inline">
                                        <?php echo $this->formRow($sanidad->get('cobertura')); ?>

                                    </label>
                                </div>

                            <label class="col-sm-2 control-label">Nombre de Obra Social</label>
                                <div class="col-sm-3">
                                    <?php echo $this->formRow($sanidad->get('obraS')->setAttributes(['placeholder' => 'Obra Social','class' => 'form-control', 'ata-minlength' => '1' ])); ?>
                                </div>
                            <label class="col-sm-2 control-label">Miembro Poseedor de la Obra Social</label>
                                <div class="col-sm-3">
                                    <?php echo $this->formRow($sanidad->get('famOS')->setAttributes(['placeholder' => 'Nombre de Persona con Obra Social','class' => 'form-control', 'ata-minlength' => '1' ])); ?>
                                </div> 
                        </div>
<!--Datos sobre la atencion medica-->
                        <div class="form-group">
                            <label class="col-sm-1 control-label">Atención en el Hospital de Catriel</label>
                                <div class="col-sm-2">
                                    <label class="radio-inline">
                                        <?php echo $this->formRow($sanidad->get('atenHC')); ?>
                                    </label>
                                </div>
                            <label class="col-sm-1 control-label">Atención en otros Centros de Salud</label>
                                <div class="col-sm-2">
                                    <label class="radio-inline">
                                        <?php echo $this->formRow($sanidad->get('otroCS')); ?>
                                    </label>
                            </div>
                            <label class="col-sm-2 control-label">Nombre del Centro de Salud</label>
                                <div class="col-sm-3">
                                    <?php echo $this->formRow($sanidad->get('nomCS')->setAttributes(['placeholder' => 'Nombre del Centro de Salud','class' => 'form-control', 'ata-minlength' => '2' ])); ?>
                                </div>
                        </div>
<!--Datos del familiar o persona con discapacidad-->
                        <div class="form-group">
                        <label class="col-sm-1 control-label">¿Tiene algun Familiar con discapacidad?</label>
                            <div class="col-sm-2">
                                <label class="radio-inline">
                                    <?php echo $this->formRow($sanidad->get('discapacidad')); ?>
                                </label>
                            </div>  
                            <label class="col-sm-2 control-label">Miembro de la Familia</label> 
                                <div class="col-sm-3">
                                    <?php echo $this->formRow($sanidad->get('famDisc')->setAttributes(['placeholder' => 'Nombre de la Persona con Discapacidad','class' => 'form-control', 'ata-minlength' => '2'])); ?>
                                </div>
                            <label class="col-sm-2 control-label">Tipo de Discapacidad</label> 
                                <div class="col-sm-3">
                                    <?php echo $this->formRow($sanidad->get('tipo')->setAttributes(['placeholder' => 'Tipo de Discapacidad','class' => 'form-control', 'ata-minlength' => '2'])); ?>
                                </div>
                            <label class="col-sm-1 control-label">¿Posee Certificado unico de Discapacidad</label>
                                <div class="col-sm-2">
                                    <label class="radio-inline">
                                        <?php echo $this->formRow($sanidad->get('certificado')); ?>
                                    </label>
                                </div> 
                        </div>
<!--Datos sobre la enfermedad-->
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Detalles de la Enfermedad</label>
                                <div class="col-sm-3">
                                 <?php echo $this->formRow($sanidad->get('detalles')->setAttributes(['placeholder' => 'Describir detalles de la enfermedad, repercusion en la familia, tipo de medicacion...etc','class' => 'form-control fullscreen'])); ?>
                                 </div>
                        </div>
<!--Otras observaciones-->
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Otras Observaciones</label>
                                <div class="col-sm-3">
                                    <?php echo $this->formRow($sanidad->get('observacion')->setAttributes(['placeholder' => 'Describir cualquier otro detalle y/o observaciones que considere necesario','class' => 'form-control fullscreen'])); ?>
                                </div>
                        </div>
<!--Inicia del boton-->
                <div class="panel-footer">
                    <div class="row">
                        <div class="col-sm-6 col-sm-offset-3">
                            <div class="btn-toolbar">
                                <button type="submit" class="btn-primary btn" >Guardar Cambios</button>
                            </div>
                        </div>
                    </div>
                    <?php echo $this->form()->closeTag(); ?> 
                </div>
<!--Finaliza Boton-->
            </div>
        </div>
</div>