<?php echo $this->flashMessenger()->render('success', array('alert', 'alert-dismissable', 'alert-success')); ?>
<?php echo $this->flashMessenger()->render('error', array('alert', 'alert-dismissable', 'alert-danger')); ?>    

           <div class="row">
                <div class="col-md-6">
                    <div class="panel panel-inverse">
                        <div class="panel-heading">
                              <h4><i class="icon-highlight fa fa-calendar"></i> Calendar</h4>
                              <div class="options">
                                <a href="javascript:;"><i class="fa fa-cog"></i></a>
                                <a href="javascript:;"><i class="fa fa-wrench"></i></a> 
                                <a href="javascript:;" class="panel-collapse"><i class="fa fa-chevron-down"></i></a>
                              </div>
                        </div>
                        <div class="panel-body" id="calendardemo">
                              <div id='calendar-drag'></div>
                        </div>
                    </div>
                </div>



                <div class="col-md-6">

                        <div class="#">               
                            <iframe style="width:300px; height:490px;" src="http://www.desarrollosocial.gob.ar/servicios/rss-y-widgets/widget-de-noticias/" width="300" height="490"></iframe>
                        </div>

                </div>  
  