
        <div class="container">

            <div class="row">
                <div class="col-md-12">
                    <p class="text-center">
                        <span class="text-info" style="font-size:2em;">Bienvenido a la</span>
                        <br>
                        <span class="text-info" style="font-size:4em;">Plataforma de Políticas Sociales</span>
                    </p>
                  
                </div>
                <div class="col-md-4 col-md-offset-4">
                    <img src="/img/fondo.png" />
                </div>
            </div>

        </div> <!-- container -->
