<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h4>Nuevo Detalle de Entrega</h4>

            </div>
            <div class="panel-body">
                <h3>Detalle</h3>
                <p class="text-primary">El Numero de Entrega es .</p>
                <br>
                <?php $form->prepare() ?>
                <?php echo $this->form()->openTag($form->setAttributes(['class' => 'form-horizontal', 'data-validate' => 'parsley', 'id' => 'validate-form'])) ?>
                <?php //var_dump($form);die;
                $registroDeEntrega = $form->get('registrodeentrega');
                ?>

                <div class="form-group">
                    <div class="col-sm-6">
                            <?php echo $this->formRow($registroDeEntrega->get('beneficiarioId')->setAttributes([ 'value' => $idBeneficiario])); ?>                        
                    </div>
                </div>
                <div class="form-group">
                    <label for="txtarea1" class="col-sm-3 control-label">Textarea</label>
                    <div class="col-sm-6">
                        <?php echo $this->formRow($registroDeEntrega->get('descripcion')->setAttributes([ 'id'=>'txtarea1', 'cols'=>'50', 'rows'=>'4', 'class'=>'form-control'])); ?>                        
                    </div>
                </div>

            </div>
            <div class="panel-footer">
                <div class="row">
                    <div class="col-sm-6 col-sm-offset-3">
                        <div class="btn-toolbar">
                            <button type="submit" class="btn-primary btn">Registrar</button>

                        </div>
                    </div>
                </div>
            </div>

<?php echo $this->form()->closeTag(); ?> 
        </div>
    </div>
</div>