<h1>Planilla de Beneficiario</h1>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-midnightblue">
            <div class="panel-body">

                <div class="row">
                    <div class="col-md-6">
                        <img src="assets/demo/avatar/johansson.png" alt="" class="pull-left" style="margin: 0 20px 20px 0">
                        <div class="table-responsive">
                            <table class="table table-condensed">
                                <h3><strong><?php echo $beneficiario[0]->getNombre(),' ', $beneficiario[0]->getApellido();?></strong></h3>
                                <!-- <thead>
                                        <tr>
                                                <th width="50%"></th>
                                                <th width="50%"></th>
                                        </tr>
                                </thead> -->
                                <tbody>
                                    <tr>
                                        <td>DNI</td>
                                        <td><?php echo $beneficiario[0]->getDni();?></td>
                                    </tr>
                                    <tr>
                                        <td>Fecha de Nacimiento</td>
                                        <?php  //Formateamos el objeto fecha solo para mostrar la fecha y no la hora
                                            $fechaDeNac  =$beneficiario[0]->getFechanac(); ?>
                                        <td><?php echo $fechaDeNac->format('d-m-Y');?></td>
                                    </tr>
                                    <tr>
                                        <td>Domicilio</td>
                                        <td><?php echo $beneficiario[0]->getDomben(); ?></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <hr>

                <div class="row">
                    <div class="col-md-12">
                    <div class="panel panel-sky">
                        <div class="panel-heading">
                            <h4>Lista de productos</h4>
                            <div class="options">   
                                <a href="javascript:;"><i class="fa fa-cog"></i></a>
                                <a href="javascript:;"><i class="fa fa-wrench"></i></a>
                                <a href="javascript:;" class="panel-collapse"><i class="fa fa-chevron-down"></i></a>
                            </div>
                        </div>
                        <div class="panel-body collapse in">
                            <?php echo $this->flashMessenger()->render('success', array('alert','alert-dismissable', 'alert-success')); ?>
                            <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered datatables" id="editable">
                                <thead>
                                    <tr>
                                        <th>Fecha de Entrega</th>
                                        <th>Detalle de entrega</th>
                                        <th>Firma?</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach($registrosDeModulos as $registroModulo): ?>
                                        <tr class="odd gradeX">
                                            <?php var_dump($registroModulo)?>
                                            <?php  $fechaEntrega =$registro->getFechaEntrega()  ?>
                                            <td><?php echo $fechaEntrega->format('d-m-Y')  ?></td>                                            
                                            <td><?php echo $registro->getItemId() ?></td>
                                            <td></td>                                                                                                                      
                                         </tr>
                                     <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div><!-- col-md-12 -->
                </div>


            </div>
        </div>
    </div>
</div>