<h1>Planilla de Beneficiario</h1>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-midnightblue">
            <div class="panel-body">

                <div class="row">
                    <div class="col-md-6">
                        <div class="table-responsive">
                            <table class="table table-condensed">
                                
                                <h3><strong><?php echo $beneficiario->getNombre(), ' ', $beneficiario->getApellido(); ?></strong> 
                                    
                                </h3>
                                <!-- <thead>
                                        <tr>
                                                <th width="50%"></th>
                                                <th width="50%"></th>
                                        </tr>
                                </thead> -->
                                <tbody>
                                    <tr>
                                        <td>DNI</td>
                                        <td><?php echo $beneficiario->getDni(); ?></td>
                                    </tr>
                                    <tr>
                                        <td>Fecha de Nacimiento</td>
                                        <?php
                                        //Formateamos el objeto fecha solo para mostrar la fecha y no la hora
                                        $fechaDeNac = $beneficiario->getFechanac();
                                        ?>
                                        <td><?php echo $fechaDeNac->format('d-m-Y'); ?></td>
                                    </tr>
                                    <tr>
                                        <td>Domicilio</td>
                                        <td><?php echo $beneficiario->getDomben(); ?></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-sky">
                            <div class="panel-heading">
                                <h4>Lista de entregas</h4>
                                <div class="options">   
                                    <a href="javascript:;"><i class="fa fa-cog"></i></a>
                                    <a href="javascript:;"><i class="fa fa-wrench"></i></a>
                                    <a href="javascript:;" class="panel-collapse"><i class="fa fa-chevron-down"></i></a>
                                </div>
                            </div>
                            <div class="panel-body collapse in">
                            <?php echo $this->flashMessenger()->render('success', array('alert', 'alert-dismissable', 'alert-success')); ?>
                                <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered datatables" id="editable">
                                    <thead>
                                        <tr>
                                            <th>Numero de Entrega</th>
                                            <th>Fecha de Entrega</th>
                                            <th>Detalle de entrega</th>
                                            <th>Firmo</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                            <?php for ($i = 0; $i < count($entrega); $i++) { ?>
                                            <tr class="odd gradeX">
                                                <td><?php echo $entrega[$i]->getIdRegistro(); ?>
                                                    <div class="btn-group">
                                                        <button type="button" class="btn btn-default dropdown-toggle btn btn-default btn-xs" data-toggle="dropdown"><i class="fa fa-plus"> </i><span class="caret"></span>
                                                        </button>
                                                        <ul class="dropdown-menu" role="menu">
                                                            <!--Opcion uno se dirige a Ingresar Nuevo Familiar-->
                                                            <li><a  href="<?php echo $this->url('editar_asistencia', array('id' => $entrega[$i]->getIdRegistro(),'idBeneficiario' => $beneficiario->getIdBeneficiario())) ?>"><i class="fa fa-cog"></i>Editar</a></li>
                                                        </ul>
                                                    </div>  
                                                </td>
                                                   <?php $fechaEntrega = $entrega[$i]->getFechaEntrega(); ?>
                                                <td><?php echo $fechaEntrega->format('d-m-Y'); ?></td>                                            
                                                <td><?php echo $entrega[$i]->getDescripcion(); ?></td>  
                                                <td></td>
                                            </tr>
                                            <?php } ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div><!-- col-md-12 -->
                </div>


            </div>
        </div>
    </div>
</div>