<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h4>Nuevo Producto</h4>

            </div>
            <div class="panel-body">
                <h3>Producto</h3>
                <p>Ingrese los datos del nuevo producto</p>
                <p class="text-primary">El ID de producto, stock se genera automáticamente y fecha de ingreso es por defecto la actual.</p>
                <br>
                <?php $form->prepare() ?>
                <?php echo $this->form()->openTag($form->setAttributes(['class' => 'form-horizontal', 'data-validate' => 'parsley', 'id' => 'validate-form'])) ?>
                <?php //var_dump($form);die;
                $registroPro = $form->get('registro-producto'); ?>

                <div class="form-group">
                    <label for="focusedinput" class="col-sm-3 control-label">Nombre del producto</label>
                    <div class="col-sm-6">
                        <?php echo $this->formRow($registroPro->get('beneficiarioId')->setAttributes([ 'value' =>  $id ])); ?>                        
                        <?php echo $this->formRow($registroPro->get('tipo')->setAttributes([ 'value' => 'producto'])); ?>
                        <?php echo $this->formRow($registroPro->get('itemId')->setAttributes([ 'id' => 'focusedinput', 'class' => 'form-control'])); ?> 
                    </div>
                </div>
                 

                <div class="form-group">
                        <label class="col-sm-3 control-label">
                            cantidad
                        </label>
                        <div class="col-sm-6">
                            <?php echo $this->formRow($registroPro->get('cantidad')->setAttributes(['ata-minlength' => '1', 'class' => 'form-control'])); ?>
                        </div>
                    </div>
            </div>
            <div class="panel-footer">
                <div class="row">
                    <div class="col-sm-6 col-sm-offset-3">
                        <div class="btn-toolbar">
                            <button type="submit" class="btn-primary btn">Registrar</button>

                        </div>
                    </div>
                </div>
            </div>
            
<?php echo $this->form()->closeTag(); ?> 
        </div>
    </div>
</div>