<html>
<style>
table { margin: auto; }
td {
  font-size: 0.8em;
  padding: 4pt;
  text-align: center;
  font-family: sans-serif;
}
</style>
<body>
<table border ="1">
<thead>
<tr>
<td colspan="20">Planilla de Asistencia</td>
</tr>
<tfoot>
<tr>
<td colspan="20">Footer</td>
</tr>
</tfoot>
<tr>
    <th>Numero de Entrega</th>
    <th>Fecha de Entrega</th>
    <th>Detalle de entreg</th>
</tr>
</thead>

<tr>
<td style="color: black;">Numero de Entrega</td>
<td style="color: black;">Fecha de Entrega</td>
<td style="color: black;">Detalle de entrega</td>
<td style="color: black;">4</td>

</tr>


</table>
</body>
</html>