<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Ejercicio2  mod 3</title>
        <link href="style.css" rel="stylesheet" type="text/css">


    </head>

    <body>
        <div id="caja">
            <header class="borde" id="headaer1">

                header
            </header>
            <div id="caja1">

                <nav class="borde" >
                    nav
                </nav>

                <section class="borde" id="sec">
                    Section



                    <header class="borde" >
                        header
                    </header class="borde">
                    <article class="borde">
                        article
                    </article>
                    <footer class="borde">
                        footer
                    </footer>
                </section>

                <aside class="borde" >
                    aside
                </aside>

            </div>
            <footer class="borde" >
                footer
            </footer>

        </div>
    </body>
</html>