<html>
<style>
table { margin: auto; }
td {
  font-size: 0.8em;
  padding: 4pt;
  text-align: center;
  font-family: sans-serif;
}
</style>
<body>
<table border ="1">
<thead>
<tr>
<td colspan="20">Planilla de Asistencia</td>
</tr>
<tfoot>
<tr><td colspan="20"><?php echo $beneficiario->getNombre(),$beneficiario->getApellido(); ?></td></tr>
<tr><td colspan="20"><?php echo $beneficiario->getDni(); ?></td></tr>
<tr><td colspan="20"><?php $fecha  = $beneficiario->getFechanac();
                                                    echo $fecha->format('d-m-Y');
                                        ?></td></tr>
<tr><td colspan="20"><?php echo $beneficiario->getDomben(); ?></td></tr>
</tfoot>
<tr>
    <th>Numero de Entrega</th>
    <th>Fecha de Entrega</th>
    <th>Detalle de entreg</th>
</tr>
</thead>

<tr>
 <tr>
<td style="color: black;">Numero de Entrega</td>
<td style="color: black;">Fecha de Entrega</td>
<td style="color: black;">Detalle de entrega</td>
</tr>
    <?php for($i = 0;$i <count($entrega);$i++){ ?>
        <tr>
        <td style="color: black;"><?php echo $entrega[$i]->getDescripcion(); ?></td>
       <td style="color: black;"><?php  $fechaE= $entrega[$i]->getFechaEntrega();
                                                            echo $fecha->format('d-m-Y');
                                                ?></td>
       <td style="color: black;"><?php echo $entrega[$i]->getDescripcion(); ?></td>
       </tr>
    <?php } ?>


</table>
</body>
</html>